export interface CountryData {
  name: string
  cities: string[]
}

export const COUNTRIES: CountryData[] = [
  { name: 'Afghanistan', cities: ['Kabul', 'Kandahar', 'Herat', 'Mazar-i-Sharif'] },
  { name: 'Albania', cities: ['Tirana', 'Durrës', 'Vlorë', 'Shkodër'] },
  { name: 'Algeria', cities: ['Algiers', 'Oran', 'Constantine', 'Annaba'] },
  { name: 'Andorra', cities: ['Andorra la Vella'] },
  { name: 'Angola', cities: ['Luanda', 'Huambo', 'Lobito', 'Benguela'] },
  { name: 'Argentina', cities: ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'Tucumán', 'Mar del Plata'] },
  { name: 'Armenia', cities: ['Yerevan', 'Gyumri', 'Vanadzor'] },
  { name: 'Australia', cities: ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Gold Coast', 'Canberra'] },
  { name: 'Austria', cities: ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Innsbruck'] },
  { name: 'Azerbaijan', cities: ['Baku', 'Ganja', 'Sumqayit'] },
  { name: 'Bahamas', cities: ['Nassau', 'Freeport'] },
  { name: 'Bahrain', cities: ['Manama', 'Riffa', 'Muharraq'] },
  { name: 'Bangladesh', cities: ['Dhaka', 'Chittagong', 'Sylhet', 'Rajshahi', 'Khulna'] },
  { name: 'Belarus', cities: ['Minsk', 'Gomel', 'Mogilev', 'Vitebsk', 'Grodno'] },
  { name: 'Belgium', cities: ['Brussels', 'Antwerp', 'Ghent', 'Bruges', 'Liège'] },
  { name: 'Belize', cities: ['Belmopan', 'Belize City'] },
  { name: 'Benin', cities: ['Cotonou', 'Porto-Novo', 'Parakou'] },
  { name: 'Bolivia', cities: ['La Paz', 'Santa Cruz', 'Cochabamba', 'Sucre', 'Oruro'] },
  { name: 'Bosnia and Herzegovina', cities: ['Sarajevo', 'Banja Luka', 'Tuzla', 'Mostar'] },
  { name: 'Botswana', cities: ['Gaborone', 'Francistown', 'Molepolole'] },
  { name: 'Brazil', cities: ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Manaus', 'Curitiba', 'Recife', 'Porto Alegre'] },
  { name: 'Brunei', cities: ['Bandar Seri Begawan'] },
  { name: 'Bulgaria', cities: ['Sofia', 'Plovdiv', 'Varna', 'Burgas'] },
  { name: 'Burkina Faso', cities: ['Ouagadougou', 'Bobo-Dioulasso'] },
  { name: 'Burundi', cities: ['Bujumbura', 'Gitega'] },
  { name: 'Cambodia', cities: ['Phnom Penh', 'Siem Reap', 'Sihanoukville'] },
  { name: 'Cameroon', cities: ['Yaoundé', 'Douala', 'Garoua', 'Bamenda'] },
  { name: 'Canada', cities: ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Edmonton', 'Ottawa', 'Quebec City', 'Winnipeg'] },
  { name: 'Cape Verde', cities: ['Praia', 'Mindelo'] },
  { name: 'Chad', cities: ["N'Djamena", 'Moundou', 'Sarh'] },
  { name: 'Chile', cities: ['Santiago', 'Valparaíso', 'Concepción', 'La Serena', 'Antofagasta', 'Temuco'] },
  { name: 'China', cities: ['Beijing', 'Shanghai', 'Guangzhou', 'Shenzhen', 'Chengdu', 'Tianjin', 'Wuhan', 'Xi\'an', 'Hangzhou', 'Nanjing', 'Hong Kong', 'Macau'] },
  { name: 'Colombia', cities: ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena', 'Cúcuta', 'Bucaramanga', 'Pereira', 'Santa Marta', 'Ibagué', 'Pasto', 'Manizales'] },
  { name: 'Comoros', cities: ['Moroni'] },
  { name: 'Congo', cities: ['Brazzaville', 'Pointe-Noire'] },
  { name: 'Costa Rica', cities: ['San José', 'Alajuela', 'Cartago', 'Heredia', 'Liberia'] },
  { name: 'Croatia', cities: ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Dubrovnik'] },
  { name: 'Cuba', cities: ['Havana', 'Santiago de Cuba', 'Camagüey', 'Holguín', 'Guantánamo'] },
  { name: 'Cyprus', cities: ['Nicosia', 'Limassol', 'Larnaca', 'Paphos'] },
  { name: 'Czech Republic', cities: ['Prague', 'Brno', 'Ostrava', 'Plzeň'] },
  { name: 'Denmark', cities: ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg'] },
  { name: 'Djibouti', cities: ['Djibouti City'] },
  { name: 'Dominican Republic', cities: ['Santo Domingo', 'Santiago', 'La Romana', 'San Pedro de Macorís', 'Punta Cana'] },
  { name: 'DR Congo', cities: ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kisangani', 'Goma'] },
  { name: 'Ecuador', cities: ['Quito', 'Guayaquil', 'Cuenca', 'Ambato', 'Manta', 'Portoviejo'] },
  { name: 'Egypt', cities: ['Cairo', 'Alexandria', 'Giza', 'Sharm el-Sheikh', 'Luxor', 'Hurghada', 'Aswan'] },
  { name: 'El Salvador', cities: ['San Salvador', 'Santa Ana', 'San Miguel', 'La Libertad'] },
  { name: 'Equatorial Guinea', cities: ['Malabo', 'Bata'] },
  { name: 'Eritrea', cities: ['Asmara', 'Keren', 'Massawa'] },
  { name: 'Estonia', cities: ['Tallinn', 'Tartu', 'Narva', 'Pärnu'] },
  { name: 'Eswatini', cities: ['Mbabane', 'Manzini'] },
  { name: 'Ethiopia', cities: ['Addis Ababa', 'Dire Dawa', 'Gondar', 'Mekele', 'Hawassa'] },
  { name: 'Fiji', cities: ['Suva', 'Nadi', 'Lautoka'] },
  { name: 'Finland', cities: ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu', 'Turku'] },
  { name: 'France', cities: ['Paris', 'Lyon', 'Marseille', 'Toulouse', 'Nice', 'Nantes', 'Bordeaux', 'Strasbourg', 'Montpellier'] },
  { name: 'Gabon', cities: ['Libreville', 'Port-Gentil', 'Franceville'] },
  { name: 'Gambia', cities: ['Banjul', 'Serekunda'] },
  { name: 'Georgia', cities: ['Tbilisi', 'Kutaisi', 'Batumi', 'Rustavi'] },
  { name: 'Germany', cities: ['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt', 'Stuttgart', 'Düsseldorf', 'Leipzig', 'Dresden', 'Bremen'] },
  { name: 'Ghana', cities: ['Accra', 'Kumasi', 'Tamale', 'Sekondi-Takoradi'] },
  { name: 'Greece', cities: ['Athens', 'Thessaloniki', 'Patras', 'Heraklion', 'Larissa', 'Rhodes'] },
  { name: 'Guatemala', cities: ['Guatemala City', 'Quetzaltenango', 'Escuintla', 'Antigua'] },
  { name: 'Guinea', cities: ['Conakry', 'Nzérékoré', 'Kankan'] },
  { name: 'Guinea-Bissau', cities: ['Bissau', 'Bafatá'] },
  { name: 'Guyana', cities: ['Georgetown', 'Linden', 'New Amsterdam'] },
  { name: 'Haiti', cities: ['Port-au-Prince', 'Cap-Haïtien', 'Gonaïves'] },
  { name: 'Honduras', cities: ['Tegucigalpa', 'San Pedro Sula', 'La Ceiba', 'Choloma'] },
  { name: 'Hungary', cities: ['Budapest', 'Debrecen', 'Miskolc', 'Szeged', 'Pécs'] },
  { name: 'Iceland', cities: ['Reykjavik', 'Akureyri', 'Kópavogur'] },
  { name: 'India', cities: ['Mumbai', 'Delhi', 'Bangalore', 'Kolkata', 'Chennai', 'Hyderabad', 'Ahmedabad', 'Pune', 'Jaipur', 'Surat', 'Lucknow', 'Kanpur', 'Goa'] },
  { name: 'Indonesia', cities: ['Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Semarang', 'Makassar', 'Palembang', 'Bali', 'Yogyakarta'] },
  { name: 'Iran', cities: ['Tehran', 'Mashhad', 'Isfahan', 'Karaj', 'Shiraz', 'Tabriz'] },
  { name: 'Iraq', cities: ['Baghdad', 'Basra', 'Mosul', 'Erbil', 'Sulaymaniyah'] },
  { name: 'Ireland', cities: ['Dublin', 'Cork', 'Limerick', 'Galway', 'Waterford'] },
  { name: 'Israel', cities: ['Tel Aviv', 'Jerusalem', 'Haifa', 'Beersheba', 'Eilat'] },
  { name: 'Italy', cities: ['Rome', 'Milan', 'Naples', 'Turin', 'Palermo', 'Genoa', 'Bologna', 'Florence', 'Venice', 'Bari'] },
  { name: 'Ivory Coast', cities: ['Abidjan', 'Bouaké', 'Daloa', 'Yamoussoukro'] },
  { name: 'Jamaica', cities: ['Kingston', 'Montego Bay', 'Portmore', 'Spanish Town'] },
  { name: 'Japan', cities: ['Tokyo', 'Osaka', 'Kyoto', 'Yokohama', 'Nagoya', 'Sapporo', 'Fukuoka', 'Hiroshima', 'Kobe', 'Sendai'] },
  { name: 'Jordan', cities: ['Amman', 'Zarqa', 'Irbid', 'Aqaba', 'Petra'] },
  { name: 'Kazakhstan', cities: ['Almaty', 'Astana', 'Shymkent', 'Karaganda'] },
  { name: 'Kenya', cities: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret'] },
  { name: 'Kosovo', cities: ['Pristina', 'Prizren', 'Peja'] },
  { name: 'Kuwait', cities: ['Kuwait City', 'Salmiya', 'Farwaniya'] },
  { name: 'Kyrgyzstan', cities: ['Bishkek', 'Osh', 'Jalal-Abad'] },
  { name: 'Laos', cities: ['Vientiane', 'Luang Prabang', 'Pakse'] },
  { name: 'Latvia', cities: ['Riga', 'Daugavpils', 'Liepāja', 'Jelgava'] },
  { name: 'Lebanon', cities: ['Beirut', 'Tripoli', 'Sidon', 'Tyre'] },
  { name: 'Lesotho', cities: ['Maseru', 'Teyateyaneng'] },
  { name: 'Liberia', cities: ['Monrovia', 'Gbarnga', 'Kakata'] },
  { name: 'Libya', cities: ['Tripoli', 'Benghazi', 'Misrata', 'Sabha'] },
  { name: 'Liechtenstein', cities: ['Vaduz', 'Schaan'] },
  { name: 'Lithuania', cities: ['Vilnius', 'Kaunas', 'Klaipėda', 'Šiauliai', 'Panevėžys'] },
  { name: 'Luxembourg', cities: ['Luxembourg City', 'Esch-sur-Alzette', 'Differdange'] },
  { name: 'Madagascar', cities: ['Antananarivo', 'Toamasina', 'Antsirabe', 'Fianarantsoa'] },
  { name: 'Malawi', cities: ['Lilongwe', 'Blantyre', 'Mzuzu', 'Zomba'] },
  { name: 'Malaysia', cities: ['Kuala Lumpur', 'George Town', 'Ipoh', 'Shah Alam', 'Johor Bahru', 'Kota Kinabalu', 'Kuching'] },
  { name: 'Maldives', cities: ['Malé', 'Addu City', 'Fuvahmulah'] },
  { name: 'Mali', cities: ['Bamako', 'Sikasso', 'Mopti', 'Koutiala'] },
  { name: 'Malta', cities: ['Valletta', 'Birkirkara', 'Mosta', 'St. Paul\'s Bay'] },
  { name: 'Mauritania', cities: ['Nouakchott', 'Nouadhibou', 'Rosso'] },
  { name: 'Mauritius', cities: ['Port Louis', 'Beau Bassin-Rose Hill', 'Vacoas-Phoenix'] },
  { name: 'Mexico', cities: ['Mexico City', 'Guadalajara', 'Monterrey', 'Cancún', 'Puebla', 'Tijuana', 'León', 'Mérida', 'Acapulco', 'Veracruz', 'Oaxaca', 'Los Cabos'] },
  { name: 'Moldova', cities: ['Chișinău', 'Bălți', 'Tiraspol'] },
  { name: 'Monaco', cities: ['Monaco'] },
  { name: 'Mongolia', cities: ['Ulaanbaatar', 'Erdenet', 'Darkhan'] },
  { name: 'Montenegro', cities: ['Podgorica', 'Nikšić', 'Herceg Novi'] },
  { name: 'Morocco', cities: ['Casablanca', 'Rabat', 'Fez', 'Marrakech', 'Agadir', 'Tangier', 'Meknes'] },
  { name: 'Mozambique', cities: ['Maputo', 'Matola', 'Nampula', 'Beira', 'Chimoio'] },
  { name: 'Myanmar', cities: ['Yangon', 'Mandalay', 'Naypyidaw', 'Bago'] },
  { name: 'Namibia', cities: ['Windhoek', 'Swakopmund', 'Rundu', 'Walvis Bay'] },
  { name: 'Nepal', cities: ['Kathmandu', 'Pokhara', 'Lalitpur', 'Bharatpur'] },
  { name: 'Netherlands', cities: ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven', 'Groningen'] },
  { name: 'New Zealand', cities: ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Tauranga', 'Dunedin'] },
  { name: 'Nicaragua', cities: ['Managua', 'León', 'Masaya', 'Matagalpa', 'Granada'] },
  { name: 'Niger', cities: ['Niamey', 'Zinder', 'Maradi', 'Agadez'] },
  { name: 'Nigeria', cities: ['Lagos', 'Abuja', 'Kano', 'Ibadan', 'Port Harcourt', 'Benin City', 'Kaduna', 'Enugu'] },
  { name: 'North Korea', cities: ['Pyongyang', 'Hamhung', 'Chongjin'] },
  { name: 'North Macedonia', cities: ['Skopje', 'Bitola', 'Kumanovo', 'Ohrid'] },
  { name: 'Norway', cities: ['Oslo', 'Bergen', 'Trondheim', 'Stavanger', 'Tromsø'] },
  { name: 'Oman', cities: ['Muscat', 'Salalah', 'Sohar', 'Nizwa'] },
  { name: 'Pakistan', cities: ['Karachi', 'Lahore', 'Faisalabad', 'Rawalpindi', 'Islamabad', 'Multan', 'Peshawar', 'Quetta'] },
  { name: 'Palestine', cities: ['Gaza', 'Ramallah', 'Nablus', 'Hebron', 'Jenin'] },
  { name: 'Panama', cities: ['Panama City', 'Colón', 'David', 'Santiago'] },
  { name: 'Papua New Guinea', cities: ['Port Moresby', 'Lae', 'Mount Hagen'] },
  { name: 'Paraguay', cities: ['Asunción', 'Ciudad del Este', 'San Lorenzo', 'Luque', 'Capiatá'] },
  { name: 'Peru', cities: ['Lima', 'Arequipa', 'Cusco', 'Trujillo', 'Chiclayo', 'Piura', 'Iquitos', 'Machu Picchu'] },
  { name: 'Philippines', cities: ['Manila', 'Quezon City', 'Davao', 'Cebu', 'Zamboanga', 'Antipolo', 'Pasig'] },
  { name: 'Poland', cities: ['Warsaw', 'Kraków', 'Łódź', 'Wrocław', 'Poznań', 'Gdańsk', 'Szczecin', 'Katowice'] },
  { name: 'Portugal', cities: ['Lisbon', 'Porto', 'Braga', 'Coimbra', 'Setúbal', 'Funchal', 'Faro', 'Algarve'] },
  { name: 'Qatar', cities: ['Doha', 'Al Wakra', 'Al Rayyan', 'Al Khor'] },
  { name: 'Romania', cities: ['Bucharest', 'Cluj-Napoca', 'Timișoara', 'Iași', 'Constanța', 'Craiova', 'Brașov'] },
  { name: 'Russia', cities: ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Nizhny Novgorod', 'Kazan', 'Chelyabinsk', 'Samara', 'Ufa', 'Rostov-on-Don'] },
  { name: 'Rwanda', cities: ['Kigali', 'Butare', 'Gitarama', 'Ruhengeri'] },
  { name: 'Saudi Arabia', cities: ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam', 'Khobar', 'Taif'] },
  { name: 'Senegal', cities: ['Dakar', 'Touba', 'Thiès', 'Kaolack', 'Ziguinchor'] },
  { name: 'Serbia', cities: ['Belgrade', 'Novi Sad', 'Niš', 'Kragujevac', 'Subotica'] },
  { name: 'Sierra Leone', cities: ['Freetown', 'Bo', 'Kenema', 'Koidu'] },
  { name: 'Singapore', cities: ['Singapore'] },
  { name: 'Slovakia', cities: ['Bratislava', 'Košice', 'Prešov', 'Žilina', 'Nitra'] },
  { name: 'Slovenia', cities: ['Ljubljana', 'Maribor', 'Celje', 'Kranj'] },
  { name: 'Somalia', cities: ['Mogadishu', 'Hargeisa', 'Kismayo', 'Bosaso'] },
  { name: 'South Africa', cities: ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Port Elizabeth', 'Bloemfontein', 'East London'] },
  { name: 'South Korea', cities: ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Ulsan', 'Jeju'] },
  { name: 'South Sudan', cities: ['Juba', 'Wau', 'Malakal'] },
  { name: 'Spain', cities: ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza', 'Málaga', 'Murcia', 'Palma', 'Bilbao', 'Ibiza', 'Granada'] },
  { name: 'Sri Lanka', cities: ['Colombo', 'Kandy', 'Galle', 'Jaffna', 'Negombo'] },
  { name: 'Sudan', cities: ['Khartoum', 'Omdurman', 'Port Sudan', 'Kassala'] },
  { name: 'Suriname', cities: ['Paramaribo', 'Lelydorp', 'Nieuw Nickerie'] },
  { name: 'Sweden', cities: ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Västerås', 'Örebro'] },
  { name: 'Switzerland', cities: ['Zurich', 'Geneva', 'Basel', 'Bern', 'Lausanne', 'Lucerne'] },
  { name: 'Syria', cities: ['Damascus', 'Aleppo', 'Homs', 'Latakia', 'Hama'] },
  { name: 'Taiwan', cities: ['Taipei', 'Kaohsiung', 'Taichung', 'Tainan', 'Hsinchu'] },
  { name: 'Tajikistan', cities: ['Dushanbe', 'Khujand', 'Kulob'] },
  { name: 'Tanzania', cities: ['Dar es Salaam', 'Dodoma', 'Mwanza', 'Zanzibar', 'Arusha', 'Kilimanjaro'] },
  { name: 'Thailand', cities: ['Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya', 'Krabi', 'Koh Samui', 'Ayutthaya', 'Chiang Rai'] },
  { name: 'Timor-Leste', cities: ['Dili', 'Baucau'] },
  { name: 'Togo', cities: ['Lomé', 'Sokodé', 'Kara'] },
  { name: 'Trinidad and Tobago', cities: ['Port of Spain', 'San Fernando', 'Chaguanas'] },
  { name: 'Tunisia', cities: ['Tunis', 'Sfax', 'Sousse', 'Djerba', 'Bizerte'] },
  { name: 'Turkey', cities: ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Antalya', 'Adana', 'Konya', 'Gaziantep', 'Trabzon', 'Cappadocia'] },
  { name: 'Turkmenistan', cities: ['Ashgabat', 'Türkmenabat', 'Mary'] },
  { name: 'Uganda', cities: ['Kampala', 'Gulu', 'Lira', 'Mbarara', 'Entebbe'] },
  { name: 'Ukraine', cities: ['Kyiv', 'Kharkiv', 'Odessa', 'Dnipro', 'Donetsk', 'Lviv', 'Zaporizhzhia'] },
  { name: 'United Arab Emirates', cities: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Ajman', 'Ras Al Khaimah', 'Fujairah'] },
  { name: 'United Kingdom', cities: ['London', 'Birmingham', 'Manchester', 'Glasgow', 'Liverpool', 'Bristol', 'Edinburgh', 'Leeds', 'Cardiff', 'Belfast'] },
  { name: 'United States', cities: ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'Miami', 'Atlanta', 'Boston', 'Las Vegas', 'Orlando', 'Seattle', 'Denver', 'Washington DC', 'San Francisco', 'Nashville', 'New Orleans'] },
  { name: 'Uruguay', cities: ['Montevideo', 'Salto', 'Ciudad de la Costa', 'Paysandú', 'Punta del Este'] },
  { name: 'Uzbekistan', cities: ['Tashkent', 'Samarkand', 'Namangan', 'Bukhara', 'Andijan'] },
  { name: 'Venezuela', cities: ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto', 'Maracay', 'Ciudad Guayana'] },
  { name: 'Vietnam', cities: ['Ho Chi Minh City', 'Hanoi', 'Da Nang', 'Hải Phòng', 'Huế', 'Nha Trang', 'Hội An'] },
  { name: 'Yemen', cities: ['Sanaa', 'Aden', 'Taiz', 'Hodeidah', 'Mukalla'] },
  { name: 'Zambia', cities: ['Lusaka', 'Kitwe', 'Ndola', 'Livingstone'] },
  { name: 'Zimbabwe', cities: ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare', 'Victoria Falls'] },
]

export const COUNTRY_NAMES = COUNTRIES.map((c) => c.name)

export function getCitiesByCountry(countryName: string): string[] {
  const found = COUNTRIES.find(
    (c) => c.name.toLowerCase() === countryName.toLowerCase()
  )
  return found ? found.cities : []
}
