export interface CountryData {
  name: string
  cities: string[]
}

export const COUNTRIES: CountryData[] = [
  { name: 'Afganistán', cities: ['Kabul', 'Kandahar', 'Herat', 'Mazar-i-Sharif'] },
  { name: 'Albania', cities: ['Tirana', 'Durrës', 'Vlorë', 'Shkodër'] },
  { name: 'Argelia', cities: ['Argel', 'Orán', 'Constantina', 'Annaba'] },
  { name: 'Andorra', cities: ['Andorra la Vella'] },
  { name: 'Angola', cities: ['Luanda', 'Huambo', 'Lobito', 'Benguela'] },
  { name: 'Argentina', cities: ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'Tucumán', 'Mar del Plata'] },
  { name: 'Armenia', cities: ['Ereván', 'Gyumri', 'Vanadzor'] },
  { name: 'Australia', cities: ['Sídney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaida', 'Gold Coast', 'Canberra'] },
  { name: 'Austria', cities: ['Viena', 'Graz', 'Linz', 'Salzburgo', 'Innsbruck'] },
  { name: 'Azerbaiyán', cities: ['Bakú', 'Ganja', 'Sumqayit'] },
  { name: 'Bahamas', cities: ['Nasáu', 'Freeport'] },
  { name: 'Baréin', cities: ['Manama', 'Riffa', 'Muharraq'] },
  { name: 'Bangladés', cities: ['Daca', 'Chittagong', 'Sylhet', 'Rajshahi', 'Khulna'] },
  { name: 'Bielorrusia', cities: ['Minsk', 'Gómel', 'Mogilev', 'Vitebsk', 'Grodno'] },
  { name: 'Bélgica', cities: ['Bruselas', 'Amberes', 'Gante', 'Brujas', 'Lieja'] },
  { name: 'Belice', cities: ['Belmopán', 'Ciudad de Belice'] },
  { name: 'Benín', cities: ['Cotonú', 'Porto-Novo', 'Parakou'] },
  { name: 'Bolivia', cities: ['La Paz', 'Santa Cruz', 'Cochabamba', 'Sucre', 'Oruro'] },
  { name: 'Bosnia y Herzegovina', cities: ['Sarajevo', 'Banja Luka', 'Tuzla', 'Mostar'] },
  { name: 'Botsuana', cities: ['Gaborone', 'Francistown', 'Molepolole'] },
  { name: 'Brasil', cities: ['São Paulo', 'Río de Janeiro', 'Brasilia', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Manaos', 'Curitiba', 'Recife', 'Porto Alegre'] },
  { name: 'Brunéi', cities: ['Bandar Seri Begawan'] },
  { name: 'Bulgaria', cities: ['Sofía', 'Plovdiv', 'Varna', 'Burgas'] },
  { name: 'Burkina Faso', cities: ['Uagadugú', 'Bobo-Dioulasso'] },
  { name: 'Burundi', cities: ['Bujumbura', 'Gitega'] },
  { name: 'Camboya', cities: ['Phnom Penh', 'Siem Reap', 'Sihanoukville'] },
  { name: 'Camerún', cities: ['Yaundé', 'Duala', 'Garoua', 'Bamenda'] },
  { name: 'Canadá', cities: ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Edmonton', 'Ottawa', 'Quebec City', 'Winnipeg'] },
  { name: 'Cabo Verde', cities: ['Praia', 'Mindelo'] },
  { name: 'Chad', cities: ["Yamena", 'Moundou', 'Sarh'] },
  { name: 'Chile', cities: ['Santiago', 'Valparaíso', 'Concepción', 'La Serena', 'Antofagasta', 'Temuco'] },
  { name: 'China', cities: ['Pekín', 'Shanghái', 'Cantón', 'Shenzhen', 'Chengdu', 'Tianjin', 'Wuhan', 'Xi\'an', 'Hangzhou', 'Nankín', 'Hong Kong', 'Macao'] },
  { name: 'Colombia', cities: ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena', 'Cúcuta', 'Bucaramanga', 'Pereira', 'Santa Marta', 'Ibagué', 'Pasto', 'Manizales'] },
  { name: 'Comoras', cities: ['Moroni'] },
  { name: 'Congo', cities: ['Brazzaville', 'Pointe-Noire'] },
  { name: 'Costa Rica', cities: ['San José', 'Alajuela', 'Cartago', 'Heredia', 'Liberia'] },
  { name: 'Croacia', cities: ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Dubrovnik'] },
  { name: 'Cuba', cities: ['La Habana', 'Santiago de Cuba', 'Camagüey', 'Holguín', 'Guantánamo'] },
  { name: 'Chipre', cities: ['Nicosia', 'Limasol', 'Lárnaca', 'Pafos'] },
  { name: 'República Checa', cities: ['Praga', 'Brno', 'Ostrava', 'Plzeň'] },
  { name: 'Dinamarca', cities: ['Copenhague', 'Aarhus', 'Odense', 'Aalborg'] },
  { name: 'Yibuti', cities: ['Yibuti'] },
  { name: 'República Dominicana', cities: ['Santo Domingo', 'Santiago', 'La Romana', 'San Pedro de Macorís', 'Punta Cana'] },
  { name: 'República Democrática del Congo', cities: ['Kinsasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kisangani', 'Goma'] },
  { name: 'Ecuador', cities: ['Quito', 'Guayaquil', 'Cuenca', 'Ambato', 'Manta', 'Portoviejo'] },
  { name: 'Egipto', cities: ['El Cairo', 'Alejandría', 'Giza', 'Sharm el-Sheikh', 'Luxor', 'Hurghada', 'Asuán'] },
  { name: 'El Salvador', cities: ['San Salvador', 'Santa Ana', 'San Miguel', 'La Libertad'] },
  { name: 'Guinea Ecuatorial', cities: ['Malabo', 'Bata'] },
  { name: 'Eritrea', cities: ['Asmara', 'Keren', 'Massawa'] },
  { name: 'Estonia', cities: ['Tallin', 'Tartu', 'Narva', 'Pärnu'] },
  { name: 'Esuatini', cities: ['Mbabane', 'Manzini'] },
  { name: 'Etiopía', cities: ['Adís Abeba', 'Dire Dawa', 'Gondar', 'Mekele', 'Hawassa'] },
  { name: 'Fiyi', cities: ['Suva', 'Nadi', 'Lautoka'] },
  { name: 'Finlandia', cities: ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu', 'Turku'] },
  { name: 'Francia', cities: ['París', 'Lyon', 'Marsella', 'Toulouse', 'Niza', 'Nantes', 'Burdeos', 'Estrasburgo', 'Montpellier'] },
  { name: 'Gabón', cities: ['Libreville', 'Port-Gentil', 'Franceville'] },
  { name: 'Gambia', cities: ['Banjul', 'Serekunda'] },
  { name: 'Georgia', cities: ['Tiflis', 'Kutaisi', 'Batumi', 'Rustavi'] },
  { name: 'Alemania', cities: ['Berlín', 'Hamburgo', 'Múnich', 'Colonia', 'Fráncfort', 'Stuttgart', 'Düsseldorf', 'Leipzig', 'Dresde', 'Bremen'] },
  { name: 'Ghana', cities: ['Acra', 'Kumasi', 'Tamale', 'Sekondi-Takoradi'] },
  { name: 'Grecia', cities: ['Atenas', 'Tesalónica', 'Patras', 'Heraclión', 'Larisa', 'Rodas'] },
  { name: 'Guatemala', cities: ['Ciudad de Guatemala', 'Quetzaltenango', 'Escuintla', 'Antigua'] },
  { name: 'Guinea', cities: ['Conakry', 'Nzérékoré', 'Kankan'] },
  { name: 'Guinea-Bisáu', cities: ['Bisáu', 'Bafatá'] },
  { name: 'Guyana', cities: ['Georgetown', 'Linden', 'New Amsterdam'] },
  { name: 'Haití', cities: ['Puerto Príncipe', 'Cap-Haïtien', 'Gonaïves'] },
  { name: 'Honduras', cities: ['Tegucigalpa', 'San Pedro Sula', 'La Ceiba', 'Choloma'] },
  { name: 'Hungría', cities: ['Budapest', 'Debrecen', 'Miskolc', 'Szeged', 'Pécs'] },
  { name: 'Islandia', cities: ['Reikiavik', 'Akureyri', 'Kópavogur'] },
  { name: 'India', cities: ['Bombay', 'Delhi', 'Bangalore', 'Calcuta', 'Chennai', 'Hyderabad', 'Ahmedabad', 'Pune', 'Jaipur', 'Surat', 'Lucknow', 'Kanpur', 'Goa'] },
  { name: 'Indonesia', cities: ['Yakarta', 'Surabaya', 'Bandung', 'Medan', 'Semarang', 'Makassar', 'Palembang', 'Bali', 'Yogyakarta'] },
  { name: 'Irán', cities: ['Teherán', 'Mashhad', 'Isfahán', 'Karaj', 'Shiraz', 'Tabriz'] },
  { name: 'Irak', cities: ['Bagdad', 'Basora', 'Mosul', 'Erbil', 'Sulaymaniyah'] },
  { name: 'Irlanda', cities: ['Dublín', 'Cork', 'Limerick', 'Galway', 'Waterford'] },
  { name: 'Israel', cities: ['Tel Aviv', 'Jerusalén', 'Haifa', 'Beerseba', 'Eilat'] },
  { name: 'Italia', cities: ['Roma', 'Milán', 'Nápoles', 'Turín', 'Palermo', 'Génova', 'Bolonia', 'Florencia', 'Venecia', 'Bari'] },
  { name: 'Costa de Marfil', cities: ['Abiyán', 'Bouaké', 'Daloa', 'Yamusukro'] },
  { name: 'Jamaica', cities: ['Kingston', 'Montego Bay', 'Portmore', 'Spanish Town'] },
  { name: 'Japón', cities: ['Tokio', 'Osaka', 'Kioto', 'Yokohama', 'Nagoya', 'Sapporo', 'Fukuoka', 'Hiroshima', 'Kobe', 'Sendai'] },
  { name: 'Jordania', cities: ['Amán', 'Zarqa', 'Irbid', 'Aqaba', 'Petra'] },
  { name: 'Kazajistán', cities: ['Almaty', 'Astana', 'Shymkent', 'Karaganda'] },
  { name: 'Kenia', cities: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret'] },
  { name: 'Kosovo', cities: ['Pristina', 'Prizren', 'Peja'] },
  { name: 'Kuwait', cities: ['Ciudad de Kuwait', 'Salmiya', 'Farwaniya'] },
  { name: 'Kirguistán', cities: ['Biskek', 'Osh', 'Jalal-Abad'] },
  { name: 'Laos', cities: ['Vientián', 'Luang Prabang', 'Pakse'] },
  { name: 'Letonia', cities: ['Riga', 'Daugavpils', 'Liepāja', 'Jelgava'] },
  { name: 'Líbano', cities: ['Beirut', 'Trípoli', 'Sidón', 'Tiro'] },
  { name: 'Lesoto', cities: ['Maseru', 'Teyateyaneng'] },
  { name: 'Liberia', cities: ['Monrovia', 'Gbarnga', 'Kakata'] },
  { name: 'Libia', cities: ['Trípoli', 'Bengasi', 'Misrata', 'Sabha'] },
  { name: 'Liechtenstein', cities: ['Vaduz', 'Schaan'] },
  { name: 'Lituania', cities: ['Vilna', 'Kaunas', 'Klaipėda', 'Šiauliai', 'Panevėžys'] },
  { name: 'Luxemburgo', cities: ['Ciudad de Luxemburgo', 'Esch-sur-Alzette', 'Differdange'] },
  { name: 'Madagascar', cities: ['Antananarivo', 'Toamasina', 'Antsirabe', 'Fianarantsoa'] },
  { name: 'Malaui', cities: ['Lilongüe', 'Blantyre', 'Mzuzu', 'Zomba'] },
  { name: 'Malasia', cities: ['Kuala Lumpur', 'George Town', 'Ipoh', 'Shah Alam', 'Johor Bahru', 'Kota Kinabalu', 'Kuching'] },
  { name: 'Maldivas', cities: ['Malé', 'Addu City', 'Fuvahmulah'] },
  { name: 'Malí', cities: ['Bamako', 'Sikasso', 'Mopti', 'Koutiala'] },
  { name: 'Malta', cities: ['La Valeta', 'Birkirkara', 'Mosta', 'Bahía de San Pablo'] },
  { name: 'Mauritania', cities: ['Nuakchot', 'Nuadibú', 'Rosso'] },
  { name: 'Mauricio', cities: ['Port Louis', 'Beau Bassin-Rose Hill', 'Vacoas-Phoenix'] },
  { name: 'México', cities: ['Ciudad de México', 'Guadalajara', 'Monterrey', 'Cancún', 'Puebla', 'Tijuana', 'León', 'Mérida', 'Acapulco', 'Veracruz', 'Oaxaca', 'Los Cabos'] },
  { name: 'Moldavia', cities: ['Chisinau', 'Bălți', 'Tiraspol'] },
  { name: 'Mónaco', cities: ['Mónaco'] },
  { name: 'Mongolia', cities: ['Ulán Bator', 'Erdenet', 'Darkhan'] },
  { name: 'Montenegro', cities: ['Podgorica', 'Nikšić', 'Herceg Novi'] },
  { name: 'Marruecos', cities: ['Casablanca', 'Rabat', 'Fez', 'Marrakech', 'Agadir', 'Tánger', 'Mequinez'] },
  { name: 'Mozambique', cities: ['Maputo', 'Matola', 'Nampula', 'Beira', 'Chimoio'] },
  { name: 'Birmania', cities: ['Rangún', 'Mandalay', 'Naipyidó', 'Bago'] },
  { name: 'Namibia', cities: ['Windhoek', 'Swakopmund', 'Rundu', 'Walvis Bay'] },
  { name: 'Nepal', cities: ['Katmandú', 'Pokhara', 'Lalitpur', 'Bharatpur'] },
  { name: 'Países Bajos', cities: ['Ámsterdam', 'Róterdam', 'La Haya', 'Utrecht', 'Eindhoven', 'Groninga'] },
  { name: 'Nueva Zelanda', cities: ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Tauranga', 'Dunedin'] },
  { name: 'Nicaragua', cities: ['Managua', 'León', 'Masaya', 'Matagalpa', 'Granada'] },
  { name: 'Níger', cities: ['Niamey', 'Zinder', 'Maradi', 'Agadez'] },
  { name: 'Nigeria', cities: ['Lagos', 'Abuya', 'Kano', 'Ibadán', 'Port Harcourt', 'Ciudad de Benín', 'Kaduna', 'Enugu'] },
  { name: 'Corea del Norte', cities: ['Pionyang', 'Hamhung', 'Chongjin'] },
  { name: 'Macedonia del Norte', cities: ['Skopie', 'Bitola', 'Kumanovo', 'Ohrid'] },
  { name: 'Noruega', cities: ['Oslo', 'Bergen', 'Trondheim', 'Stavanger', 'Tromsø'] },
  { name: 'Omán', cities: ['Mascate', 'Salalah', 'Sohar', 'Nizwa'] },
  { name: 'Pakistán', cities: ['Karachi', 'Lahore', 'Faisalabad', 'Rawalpindi', 'Islamabad', 'Multan', 'Peshawar', 'Quetta'] },
  { name: 'Palestina', cities: ['Gaza', 'Ramala', 'Nablus', 'Hebrón', 'Yenín'] },
  { name: 'Panamá', cities: ['Ciudad de Panamá', 'Colón', 'David', 'Santiago'] },
  { name: 'Papúa Nueva Guinea', cities: ['Port Moresby', 'Lae', 'Mount Hagen'] },
  { name: 'Paraguay', cities: ['Asunción', 'Ciudad del Este', 'San Lorenzo', 'Luque', 'Capiatá'] },
  { name: 'Perú', cities: ['Lima', 'Arequipa', 'Cusco', 'Trujillo', 'Chiclayo', 'Piura', 'Iquitos', 'Machu Picchu'] },
  { name: 'Filipinas', cities: ['Manila', 'Quezon City', 'Dávao', 'Cebú', 'Zamboanga', 'Antipolo', 'Pasig'] },
  { name: 'Polonia', cities: ['Varsovia', 'Cracovia', 'Łódź', 'Breslavia', 'Poznań', 'Gdańsk', 'Szczecin', 'Katowice'] },
  { name: 'Portugal', cities: ['Lisboa', 'Oporto', 'Braga', 'Coímbra', 'Setúbal', 'Funchal', 'Faro', 'Algarve'] },
  { name: 'Catar', cities: ['Doha', 'Al Wakrah', 'Al Rayyan', 'Al Khor'] },
  { name: 'Rumania', cities: ['Bucarest', 'Cluj-Napoca', 'Timișoara', 'Iași', 'Constanza', 'Craiova', 'Brașov'] },
  { name: 'Rusia', cities: ['Moscú', 'San Petersburgo', 'Novosibirsk', 'Ekaterimburgo', 'Nizhny Novgorod', 'Kazán', 'Cheliábinsk', 'Samara', 'Ufá', 'Rostov del Don'] },
  { name: 'Ruanda', cities: ['Kigali', 'Butare', 'Gitarama', 'Ruhengeri'] },
  { name: 'Arabia Saudita', cities: ['Riad', 'Yeda', 'La Meca', 'Medina', 'Dammam', 'Khobar', 'Taif'] },
  { name: 'Senegal', cities: ['Dakar', 'Touba', 'Thiès', 'Kaolack', 'Ziguinchor'] },
  { name: 'Serbia', cities: ['Belgrado', 'Novi Sad', 'Niš', 'Kragujevac', 'Subotica'] },
  { name: 'Sierra Leona', cities: ['Freetown', 'Bo', 'Kenema', 'Koidu'] },
  { name: 'Singapur', cities: ['Singapur'] },
  { name: 'Eslovaquia', cities: ['Bratislava', 'Košice', 'Prešov', 'Žilina', 'Nitra'] },
  { name: 'Eslovenia', cities: ['Liubliana', 'Maribor', 'Celje', 'Kranj'] },
  { name: 'Somalia', cities: ['Mogadiscio', 'Hargeisa', 'Kismayo', 'Bosaso'] },
  { name: 'Sudáfrica', cities: ['Johannesburgo', 'Ciudad del Cabo', 'Durban', 'Pretoria', 'Port Elizabeth', 'Bloemfontein', 'East London'] },
  { name: 'Corea del Sur', cities: ['Seúl', 'Busán', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Ulsan', 'Jeju'] },
  { name: 'Sudán del Sur', cities: ['Yuba', 'Wau', 'Malakal'] },
  { name: 'España', cities: ['Madrid', 'Barcelona', 'Valencia', 'Sevilla', 'Zaragoza', 'Málaga', 'Murcia', 'Palma', 'Bilbao', 'Ibiza', 'Granada'] },
  { name: 'Sri Lanka', cities: ['Colombo', 'Kandy', 'Galle', 'Jaffna', 'Negombo'] },
  { name: 'Sudán', cities: ['Jartum', 'Omdurmán', 'Puerto Sudán', 'Kassala'] },
  { name: 'Surinam', cities: ['Paramaribo', 'Lelydorp', 'Nieuw Nickerie'] },
  { name: 'Suecia', cities: ['Estocolmo', 'Gotemburgo', 'Malmö', 'Upsala', 'Västerås', 'Örebro'] },
  { name: 'Suiza', cities: ['Zúrich', 'Ginebra', 'Basilea', 'Berna', 'Lausana', 'Lucerna'] },
  { name: 'Siria', cities: ['Damasco', 'Alepo', 'Homs', 'Latakia', 'Hama'] },
  { name: 'Taiwán', cities: ['Taipéi', 'Kaohsiung', 'Taichung', 'Tainan', 'Hsinchu'] },
  { name: 'Tayikistán', cities: ['Dusambé', 'Khujand', 'Kulob'] },
  { name: 'Tanzania', cities: ['Dar es Salaam', 'Dodoma', 'Mwanza', 'Zanzíbar', 'Arusha', 'Kilimanjaro'] },
  { name: 'Tailandia', cities: ['Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya', 'Krabi', 'Koh Samui', 'Ayutthaya', 'Chiang Rai'] },
  { name: 'Timor Oriental', cities: ['Dili', 'Baucau'] },
  { name: 'Togo', cities: ['Lomé', 'Sokodé', 'Kara'] },
  { name: 'Trinidad y Tobago', cities: ['Puerto España', 'San Fernando', 'Chaguanas'] },
  { name: 'Túnez', cities: ['Túnez', 'Sfax', 'Susa', 'Yerba', 'Bizerta'] },
  { name: 'Turquía', cities: ['Estambul', 'Ankara', 'Esmirna', 'Bursa', 'Antalya', 'Adana', 'Konya', 'Gaziantep', 'Trabzon', 'Capadocia'] },
  { name: 'Turkmenistán', cities: ['Asjabad', 'Türkmenabat', 'Mary'] },
  { name: 'Uganda', cities: ['Kampala', 'Gulu', 'Lira', 'Mbarara', 'Entebbe'] },
  { name: 'Ucrania', cities: ['Kiev', 'Járkov', 'Odesa', 'Dnipró', 'Donetsk', 'Leópolis', 'Zaporiyia'] },
  { name: 'Emiratos Árabes Unidos', cities: ['Dubái', 'Abu Dabi', 'Sharjah', 'Ajman', 'Ras Al Khaimah', 'Fujairah'] },
  { name: 'Reino Unido', cities: ['Londres', 'Birmingham', 'Mánchester', 'Glasgow', 'Liverpool', 'Bristol', 'Edimburgo', 'Leeds', 'Cardiff', 'Belfast'] },
  { name: 'Estados Unidos', cities: ['Nueva York', 'Los Ángeles', 'Chicago', 'Houston', 'Phoenix', 'Filadelfia', 'San Antonio', 'San Diego', 'Dallas', 'Miami', 'Atlanta', 'Boston', 'Las Vegas', 'Orlando', 'Seattle', 'Denver', 'Washington DC', 'San Francisco', 'Nashville', 'Nueva Orleans'] },
  { name: 'Uruguay', cities: ['Montevideo', 'Salto', 'Ciudad de la Costa', 'Paysandú', 'Punta del Este'] },
  { name: 'Uzbekistán', cities: ['Taskent', 'Samarcanda', 'Namangan', 'Bujará', 'Andijan'] },
  { name: 'Venezuela', cities: ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto', 'Maracay', 'Ciudad Guayana'] },
  { name: 'Vietnam', cities: ['Ho Chi Minh', 'Hanói', 'Da Nang', 'Hải Phòng', 'Huế', 'Nha Trang', 'Hội An'] },
  { name: 'Yemen', cities: ['Saná', 'Adén', 'Taiz', 'Hodeida', 'Mukalla'] },
  { name: 'Zambia', cities: ['Lusaka', 'Kitwe', 'Ndola', 'Livingstone'] },
  { name: 'Zimbabue', cities: ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare', 'Victoria Falls'] },
]

export const COUNTRY_NAMES = COUNTRIES.map((c) => c.name)

export function getCitiesByCountry(countryName: string): string[] {
  const found = COUNTRIES.find(
    (c) => c.name.toLowerCase() === countryName.toLowerCase()
  )
  return found ? found.cities : []
}
