export interface ServiceItem {
  name: string
  price: number
  cost: number
  description?: string
}

// Normaliza nombre para comparación: sin tildes, minúsculas, espacios simples
export function normalizeServiceName(s: string): string {
  return (s || '')
    .trim()
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '') // elimina diacríticos/tildes
    .replace(/\s+/g, ' ')            // colapsa espacios múltiples
}

export const SERVICES: ServiceItem[] = [
  { name: '4 ISLAS MARITIMO', price: 220000, cost: 150000 },
  { name: '5 DESTINOS TERRESTRE', price: 250000, cost: 180000 },
  { name: '5 ISLAS BASIC', price: 270000, cost: 210000 },
  { name: '5 islas full day marítimo', price: 280000, cost: 196000, description: `¡Explora lo mejor de las Islas del Rosario en un solo día!\nEste tour está diseñado para quienes quieren vivir una experiencia inolvidable, llena de paisajes espectaculares, playas privadas, actividades acuáticas y momentos únicos en el mar.\nDurante este increíble recorrido disfrutarás de islas paradisíacas, snorkeling, visita a lugares icónicos y el mágico avistamiento del plancton bioluminiscente al caer la noche.\n¡Un día perfecto para compartir con amigos, familia o pareja!\n🌟 Incluye:\n🚌 Recogida en bus climatizado por la zona hotelera o punto acordado\n🚤 Salida desde muelle asignado\n🏰 Panorámico Fuerte de Bocachica\n🏝️ Panorámico Islas del Rosario\n🌅 Isla privada Kokomo (50 min)\n🤿 Snorkeling o acuario (30 min)*\n✈️ Avistamiento de avioneta de Pablo Escobar en Isla Naval\n🏝️ Visita a Isla Cholón (50 min)\nCóctel de mariscos\nBohío compartido\n🏖️ Playa Tranquila\nAlmuerzo típico\nUso de instalaciones\n✨ Snack + Avistamiento del plancton bioluminiscente (25 min)\n🚌 Retorno a Cartagena en bus climatizado\n🕒 Horario del tour:\n7:00 a.m. – 8:00 p.m.\n⚠️ Observaciones importantes:\nLa visita al acuario no está incluida (valor: $40.000 COP).\nQuienes deseen ir al acuario deben informar al guía en el bus.\nLa actividad de snorkeling dura 50 minutos; si asistes al acuario, pierdes el snorkel.` },
  { name: '5 ISLAS OPEN BAR', price: 380000, cost: 300000 },
  { name: '5 ISLAS PREMIUM OPEN  BAR', price: 380000, cost: 266000, description: `¡Vive la aventura náutica más completa en Cartagena!\nDisfruta un recorrido inolvidable por las aguas cristalinas del Caribe, explorando las Islas del Rosario y lugares icónicos como Cholon y Barú. Sumérgete en arrecifes coralinos, descubre la avioneta sumergida y relájate en playas paradisíacas. Todo esto acompañado de guía bilingüe, comodidad y diversión a bordo. ¡Ideal para celebrar momentos únicos como cumpleaños o pedidas de mano!\nIncluye:\n🗣️ Guía orientador en inglés y español\n🏨 Recogida en hotel desde las 7:30 a.m. (zonas: Boquilla, Crespo, Marbella, Bocagrande, Laguito, Castillo Grande, Manga)\n⏰ Zarpe 9:00 a.m. desde marina privada\n🚤 Bote deportivo\n🏰 Vista panorámica de las Fortalezas de Bocachica (Isla Tierra Bomba)\n🏝️ Vista panorámica de las 28 Islas del Rosario\n🤿 Snorkeling en arrecifes coralinos\n🤿 Snorkeling en la avioneta sumergida\n🏝️ Parada en Isla Cholon\n🏝️ Parada en Isla Agua Azul\n🏝️ 🍛 Parada en Playa Tranquila (Isla Barú) con almuerzo incluido\n🎉 Decoración especial para cumpleaños y pedidas de mano 💍\n🛥️ Retorno 4:00 p.m. al muelle Bodeguita (no incluye retorno al hotel)\nIncluye impuesto de muelle\nOPEN BAR a bordo: cervezas, gaseosas y agua (hasta agotar existencia)` },
  { name: '5 ISLAS VIP + PLANTON', price: 380000, cost: 300000 },
  { name: 'ATARDECER EN CATAMARAN SAN JUAN', price: 180000, cost: 125999, description: `Incluye:\n2 horas de recorrido por la bahía interna de Cartagena.\n2 bebidas por persona de bienvenida (botella de agua, gaseosa o cerveza).\nPasabocas (mini fritos típicos).\nBarra libre en cócteles con y sin alcohol.\nDJ en vivo + animación.\nIngreso a discoteca (preguntar directamente con el personal del barco).\nSalidas: martes a domingos.\nEncuentro: 5:00 pm – Muelle de la Bodeguita puerta N°4.\nZarpe: 5:30 pm | Regreso: 7:30 pm.\nNo incluye: tasa portuaria 18.000 COP por persona (sujeto a cambios por Corpoturismo) y debe pagarse en efectivo.` },
  { name: 'ATOLON BEACH CLUB', price: 350000, cost: 300000 },
  { name: 'AVIARIO + BARU', price: 160000, cost: 90000 },
  { name: 'BARU + ISLAS DEL ROSARIO TERRESTRE', price: 180000, cost: 110000 },
  { name: 'BORA BORA BEACH CLUB', price: 390000, cost: 310000 },
  { name: 'BORA BORA BEACH VIP', price: 490000, cost: 420000 },
  { name: 'BUCEO EN BARU', price: 330000, cost: 250000 },
  { name: 'CATAMARA SAN JUAN', price: 180000, cost: 120000 },
  { name: 'CHIVA RUMBERA', price: 50000, cost: 30000, description: `¡Embárcate en una experiencia inolvidable a bordo de la Chiva Rumbera!\nDescubre la magia nocturna de Cartagena mientras recorres sus lugares más emblemáticos en un ambiente lleno de música, alegría y diversión. Vive la tradición de la chiva con un toque moderno: DJ y animador a bordo para que la fiesta nunca pare.\nHorarios:\n🕖 07:00 pm – 09:00 pm\nParadas:\nBotas Viejas\nCastillo de San Felipe\nLetras de Cartagena\n🕘 09:15 pm – 11:00 pm\nParadas:\nBotas Viejas\nLetras de Cartagena\nIncluye:\n🚌 Recorrido por Bocagrande, Torre del Reloj, Muelle de los Pegasos, Centro de Convenciones y Calle del Arsenal\n🏰 Recorrido panorámico por las murallas de Cartagena\n🎶 Animador/DJ a bordo con música para ambientar el recorrido\n📸 Paradas de 10 minutos para tomar fotografías\n🚏 Recogida en puntos de encuentro autorizados\n🎉 Finaliza en una discoteca (opcional) o en los mismos puntos de recogida\nImportante:\nNo incluye bebidas ni comida (puedes llevar las tuyas)\nComunícate por WhatsApp para confirmar el punto de encuentro más cercano según tu hotel\n¡Una experiencia única para vivir la esencia festiva de Cartagena! 🌟` },
  { name: 'City Tour Personalizado en Cartagena', price: 280000, cost: 196000, description: `¡Descubre la historia y el encanto de Cartagena con la comodidad que mereces!\nEste recorrido está diseñado para grupos pequeños de hasta 4 personas, ideal para familias o amigos que buscan flexibilidad y atención exclusiva. Explora los lugares más emblemáticos y añade los sitios que desees visitar, todo en transporte climatizado tipo Uber o taxi driver.\n✨ Incluye:\n✅ Recorrido panorámico por:\nCastillo San Felipe de Barajas (no incluye ingreso)\nConvento de la Popa\nBarrio Getsemaní\nTorre del Reloj\nFuerte San Sebastián en Manga\nMuseo de la Esmeralda\n✅ Opción de visitar otros sitios a elección\n✅ Duración: 3 horas\n✅ Transporte climatizado tipo Uber o taxi driver\n✅ Botella de agua por persona\n✅ Aplica para grupos de máximo 4 personas\n📌 Ideal para:\nFamilias\nGrupos de amigos\nViajeros que buscan un recorrido exclusivo y flexible` },
  { name: 'CITY TOURS BARRANQUILLA/SANTA MARTA', price: 280000, cost: 210000 },
  { name: 'CITY TOURS CARTAGENA EN CHIVA', price: 90000, cost: 62999, description: `¡Descubre Cartagena como nunca antes!\nEmbárcate en nuestro City Tour en Chiva Turística, el transporte típico y colorido que te conecta con la esencia caribeña. Vive una experiencia única con:\n📸 Paradas fotográficas en la Bahía, las Botas Viejas y las icónicas letras de Cartagena.\n🏰 Visita al imponente Castillo de San Felipe y la histórica Iglesia San Pedro Claver.\n👣 Caminata guiada por el Centro Histórico.\nHorarios flexibles: 9:00 a.m. - 1:00 p.m. | 2:00 p.m. - 6:00 p.m.\n¡Reserva ahora y siente la magia de Cartagena! 🌴✨` },
  { name: 'CITY TOURS LITE', price: 90000, cost: 60000 },
  { name: 'CITY TOURS PALENQUE', price: 345000, cost: 300000 },
  { name: 'CITY TOURS PERSONALIZADO X4', price: 280000, cost: 200000 },
  { name: 'CITY TOURS PREMIUM GRUPAL', price: 1100000, cost: 950000 },
  { name: 'Day Pass Catamarán Bona Vida islas del rosario', price: 430000, cost: 301000, description: `Pasadía a islas del rosario en Catamarán Bonavida:⚓🛥️💙\nEmbárcate en una experiencia inolvidable desde las 8:00 A.M. (debes presentarte con anticipación) hasta las 4:00 P.M., navegando en un catamarán desde Cartagena hacia las Islas del Rosario. Disfruta de dos paradas, una frente a Isla Grande y otra en Punta Gigante, donde podrás sumergirte en las aguas cristalinas para explorar la vida marina con el equipo de snorkel proporcionado. A bordo, deleita tu paladar con un surtido de snacks, que incluyen empanaditas, quibbe y deditos de queso, mientras disfrutas de la barra libre de bebidas no alcohólicas que ofrece agua, gaseosas, limonada natural y jugo de temporada. Para el almuerzo, tienes la opción de saborear un delicioso arroz con mariscos o arroz con vegetales.\nMientras te relajas en el catamarán, puedes adquirir (comprar) bebidas alcohólicas adicionales y deleitarte con las vistas panorámicas del Caribe colombiano. Esta experiencia te permite disfrutar de la belleza natural de las Islas del Rosario, explorar sus aguas cristalinas y relajarte en un entorno paradisíaco, todo ello mientras disfrutas de la comodidad y los servicios ofrecidos a bordo del catamarán.\nDetalles de la actividad:\nEmbarque: 8:00 A.M. en el Muelle la Bodeguita\nZarpe: 8:30 A.m y Desembarque: 04:00 P.m\nEl recorrido es hacia Isla Grande y hacia Punta Gigante\n· Cóctel de bienvenida\n· Bebidas no alcohólicas\n· Aperitivo y almuerzo (arroz de marisco, o de pollo o vegetariano) a bordo\n· Snorkeling, mascara y tubo gratuito.\n· Tasa de embarque (18.000 COP)\n· Tasa entrada al PNN Islas del Rosario (13.500 COP)\nNota: está prohibido el ingreso de alimentos o bebidas` },
  { name: 'DAYPASS PLAYA BLANCA BARU', price: 100000, cost: 70000, description: `Disfruta un día espectacular en Playa Blanca Barú, una de las playas más hermosas del Caribe colombiano, famosa por su arena blanca, aguas cristalinas y ambiente tropical perfecto para desconectarte y relajarte. Este tour incluye transporte cómodo, gastronomía caribeña y acompañamiento profesional durante toda la experiencia.\n✨ Incluye:\n🚌 Recogida en hotel\nSectores: Bocagrande, Castillo Grande, Laguito, Boquilla, Crespo, Marbella o punto acordado.\n🚐 Transporte ida y vuelta en bus climatizado\nHasta Barú – Playa Blanca.\n🍽️ Almuerzo típico caribeño – 4 opciones:\nPollo\nPescado\nCerdo\nVegetariano\nGuía turístico acompañante\nDía libre para disfrutar del mar, playa y fotografía.\n⏰ Horario:\n7:00 a.m. – 3:00 p.m.\nNo incluye: carpas y parasoles` },
  { name: 'ETEKA BEACH CLUB', price: 300000, cost: 260000, description: `¡Escápate a la tranquilidad del paraíso!\nA solo 10 minutos en lancha desde Cartagena, disfruta un día lleno de relax y diversión en un entorno natural y exclusivo. Perfecto para quienes buscan desconectarse y recargar energía frente al mar, con música chillout y gastronomía deliciosa.\nIncluye:\n🚤 Transporte en lancha (ida y regreso)\n🍹 Cóctel de bienvenida\n🥤 Bebida no alcohólica para acompañar el almuerzo\n🏖️ Acceso a 2 playas y piscina\n🍽️ Almuerzo de 2 tiempos (plato fuerte y postre) con opciones variadas\n🎶 DJ en vivo los sábados y diferentes ambientes musicales (Chillout y Crossover)\n🛏️ 1 toalla por persona` },
  { name: 'HELICOPTERO CARTAGENA', price: 420000, cost: 350000 },
  { name: 'IBBIZA BEACH', price: 370000, cost: 300000 },
  { name: 'ISLA PALMA', price: 495000, cost: 420000, description: `Recogida: Bocagrande, Laguito, Castillo Grande y Marbella desde las 5:30 a.m.\n📍 Punto de encuentro: Muelle La Bodeguita, puerta #2 (5:45 a.m.)\n✅ El servicio incluye:\nGuía profesional durante el recorrido\nTraslado desde el hotel hasta el muelle\nSnack de frutas antes del embarque\nNavegación panorámica por Islas del Rosario y Archipiélago de San Bernardo\nAcceso exclusivo al Hotel Isla Palma (Reserva Natural)\nCoctel de bienvenida\nAlmuerzo gourmet: proteína a elección (carne, pollo o pescado), acompañantes, barra de ensaladas, jugo y postre típico\nTiempo libre en playa de arena blanca y aguas cristalinas (ideal para snorkeling – traer kit personal)\nVisita opcional al BioParque (costo adicional $20.000 COP) con recorrido educativo sobre fauna y flora local\n🔙 Retorno a Cartagena:\nSalida del hotel: 2:00 p.m. – 2:30 p.m.\nLlegada aproximada: 4:30 p.m. – 5:00 p.m.\n⚠️ No incluye:\nTasa portuaria: $37.000 COP por persona\n📌 Recomendaciones y condiciones:\nUsar ropa cómoda, protector solar y calzado adecuado\nReserva con 50% de anticipo\nCancelaciones con mínimo 24 h de anticipación (70% devolución)\nNiños de 3 a 6 años tarifa especial; mayores de 7 años tarifa completa\nProhibido ingreso de alimentos, bebidas y equipos de sonido\nServicio sujeto a condiciones climáticas y disposiciones marítimas` },
  { name: 'ISLABELA BEACH', price: 420000, cost: 360000 },
  { name: 'ISLAS DEL ROSARIO + PLAYA BLANCA BARU MARITIMO', price: 170000, cost: 118999, description: `INCLUYE\n✔️Guía acompañante.🚶🏽♂️\n✔️ Recogida al hotel 🏨; sector (Bocagrande, laguito y castillo)🚌; en caso de estar fuera estos límites deben llegar al muelle la bodeguita.\n✔️Recorrido en lancha🚤\n✔️ Visita isla San Martín de Pajarales instalaciones del oceanario. Opcional/adicional actividad del Oceanario🐬 o Actividad snorkeling 🤿\n✔️ 🏝️Visita isla  Baru-playa blanca.\n✔️Almuerzo: Opción pollo, pescado o vegetariano; acompañado con arroz con coco, patacones, ensalada y una limonada.\nNO INCLUYE\n❌Impuesto Turístico\n❌ *Actividad Opcionales/ Adicional*\n✓Actividad de Snorkeling 🤿\nPor personas $50.000\n✓Oceanario🐬\nAdulto $40.000\nNiñ@s $30.000, de 2 a 10años\n❌Retorno al hotel 🏨\nNOTA: Todos niñ@ desde los 2 años debe ir pagando porque es contado por capitanía de puerto como una vida y por seguridad de usted como visitante y de nosotros como agencia. Además si el niñ@ mide un metro debe pagar el impuesto turístico` },
  { name: 'ISLAS DEL ROSARIO FULL ADVENTURE', price: 270000, cost: 190000, description: `Tour Islas del Rosario - Full Adventure 🌴☀️\n¡Vive un día inolvidable en el paraíso! Disfruta de una experiencia completa explorando la belleza de Cartagena y sus islas.\nEl plan incluye:\n• 🚐 Transporte: Recogida en la zona hotelera.\n• 🏝️ Destinos: Visita a Isla Barú (Playa Blanca) y recorrido panorámico por las Islas del Rosario.\n• 🐬 Oceanario: Entrada incluida (estancia de 1h 30min).\n• 🤿 Snorkel: Explora los arrecifes de coral y peces de colores (incluye fotos acuáticas).\n• 🦝 Naturaleza: Avistamiento de mapaches (incluye fotos).\n• 🍽️ Almuerzo: Deliciosa comida en Playa Blanca con mesa reservada en 2do piso y vista al mar.\nHorario: 07:00 A.M. – 04:30 P.M.` },
  { name: 'ISLAS DEL ROSARIO MARITIMO', price: 160000, cost: 120000 },
  { name: 'LUXURY AMBIENTE VIP', price: 490000, cost: 410000 },
  { name: 'LUXURY BEACH', price: 430000, cost: 370000, description: `NCLUYE:\n🚤 Transporte en Lancha TRITÓN (ida y vuelta)\nSalida desde el muelle y viaje cómodo y seguro hacia uno de los paraísos más hermosos del Caribe.\n🍹 Barra Abierta Ilimitada – Bebida Nacional\nDisfruta sin límites durante toda tu estadía:\nMargaritas tradicionales\nCuba Libre\nMojitos (cóctel y versión sin licor)\nCerveza del día\nAgua y gaseosa embotellada\nDispensador de jugo de naranja\n🍽️ 4 Opciones de Almuerzo a Elegir\nPreparadas al momento:\nFilete de pesca a la plancha\nPollo a la plancha\nArroz de mariscos\nArroz con vegetales\n🏖️ Comodidad en la Playa\nParasol y asoleadora playera individuales\nAcceso a zonas exclusivas\nServicio directo en la barra\n🚿 Ducha de Agua Dulce\nIdeal para refrescarte después del mar (lleva tu toalla).\n⚓ Opcional:\nTour panorámico por Islas del Rosario o traslado al Oceanario\nDuración: 60 minutos` },
  { name: 'MANGATA BEACH', price: 420000, cost: 360000 },
  { name: 'MANTAS BEACH', price: 400000, cost: 330000, description: `Disfruta un día exclusivo en Mantas Beach, ubicado en la paradisíaca Isla Grande, con playa de arena blanca y aguas cristalinas. Este plan está diseñado para quienes buscan confort, diversión y un ambiente premium frente al mar.\n✨ Incluye:\n🚤 Transporte en lancha rápida ida y vuelta\n🥂 Copa de champaña o limonada de bienvenida\n🍽️ Almuerzo a la carta (8 opciones con bebida)\n🛌 Asoleadora (costo adicional primera fila)\n🏄 Actividades acuáticas: Paddleboards y kayaks\n🚿 Duchas de agua dulce\n🐠 Traslado al Oceanario\n🏖️ Áreas comunes:\nBaños\nComedores\nZona de playa\nRestaurante en segundo piso\nMuelle privado\nBeach bar\n🎶 DJ’s en vivo todos los días\n🍹 Promociones:\n2x1 en cócteles seleccionados\n6x5 en cervezas\n⏰ Horario:\nSalida: 7:30 a.m. desde Muelle Todomar\nRegreso aproximado: 4:00 p.m.\n📌 No incluye: tarifa administrativa, entrada al Oceanario, servicio de toallas ni actividades adicionales.` },
  { name: 'MARGARITA BEACH', price: 180000, cost: 130000 },
  { name: 'NOCHE BLANCA BEQUIA', price: 300000, cost: 240000 },
  { name: 'PALMARITO BEACH', price: 260000, cost: 200000 },
  { name: 'PALMARITO BEACH VIP', price: 340000, cost: 280000 },
  { name: 'PAO PAO BEACH CLUB', price: 390000, cost: 310000 },
  { name: 'Pasadía IBBIZA Island Beach Club', price: 370000, cost: 258999, description: `¡Haz una pausa y regálate un día de lujo en IBBIZA Island Beach Club!\nSumérgete en un ambiente exclusivo donde el confort, la buena vibra y la belleza natural del Caribe se combinan para ofrecerte una experiencia verdaderamente inolvidable.\nRelájate en camas balinesas frente al mar, disfruta de gastronomía exquisita y déjate envolver por los sonidos del océano mientras te desconectas del ritmo de la ciudad. Ya sea que quieras descansar, celebrar o pasar un día especial con amigos, IBBIZA es el lugar perfecto.\n🌟 ¿Qué disfrutarás en tu Pasadía?\n✨ Acceso a instalaciones exclusivas del beach club\n✨ Zona de playa con camas y sillas asoleadoras\n✨ Piscina con vista al mar\n✨ Cóctel de bienvenida\n✨ Almuerzo tipo gourmet según menú del día\n✨ Música ambiente y atmósfera relajada\n✨ Atención personalizada durante toda tu estadía\n📌 Perfecto para:\nParejas que buscan un día romántico\nViajeros que quieren conocer un beach club de lujo\nAmigos que desean un día de disfrute y buena vibra\nVive la experiencia IBBIZA: elegancia, mar y desconexión en un solo lugar.\nReserva ahora y asegura tu día en este rincón paradisíaco. 🌴🍹🔥` },
  { name: 'PASADIA PLAYA BLANCA', price: 100000, cost: 60000 },
  { name: 'PASADIA PLAYA TRANQUILA', price: 170000, cost: 95000 },
  { name: 'PASADIA PUNTA ARENA', price: 80000, cost: 50000 },
  { name: 'PAUE BEACH', price: 470000, cost: 380000, description: `¡Vive un día de ensueño en las Islas del Rosario! 🌴✨\nEscápate a un paraíso natural y disfruta de una experiencia única frente al mar. Relájate en playas de arena blanca, saborea un almuerzo típico y diviértete con actividades acuáticas en un entorno exclusivo. Todo con transporte seguro y atención personalizada para que tu día sea inolvidable.\nIncluye:\n✅ Transporte marítimo ida y regreso\n✅ Cóctel de bienvenida\n✅ Almuerzo típico con opciones deliciosas\n✅ Acceso a instalaciones y zonas de descanso\n✅ Actividades como kayak, paddle board y beach tennis\n✅ Botella de agua por persona\n📌 Ideal para:\nFamilias\nParejas\nAmigos que buscan desconectarse y disfrutar la magia del Caribe\n¡Reserva ahora y vive la experiencia que estabas esperando! 🌊🍹` },
  { name: 'PLAYA TRANQUILA + OCEANARIO MAR', price: 200000, cost: 160000 },
  { name: 'PLAYA TRANQUILA +MAPACHES + BAJO', price: 270000, cost: 190000 },
  { name: 'PLAYA TRANQUILA PACK X 4 ADVENTURE', price: 1050000, cost: 735000, description: `Vive una experiencia personalizada en Playa Tranquila, Barú 🌊✨, perfecta para quienes buscan comodidad, buen servicio y contacto con la naturaleza. Relájate en nuestras asoleadoras 😎, disfruta áreas de descanso 🌴, observa manglares y mapaches 🐾🌿 y sumérgete en una aventura de snorkel entre peces tropicales 🐠🤿. Un plan ideal para desconectar, disfrutar y recibir atención dedicada durante todo el día.\nIncluye:\n🤝 Servicio personalizado\n😎 Asoleadoras y zonas de descanso\n🐾 Avistamiento de manglares y mapaches\n🤿 Snorkel con peces tropicales\n🏝️ Acceso a instalaciones\n🌤️ Áreas sociales y espacios sombreados` },
  { name: 'ROSARIO BEACH', price: 370000, cost: 300000, description: `¡Disfruta un día inolvidable en Rosario Beach! 🌴☀️\nEscápate a las Islas del Rosario y vive una experiencia única frente al mar. Relájate en playas paradisíacas, saborea un almuerzo típico y disfruta de actividades acuáticas en un entorno exclusivo. Todo con transporte seguro y atención personalizada para que tu día sea perfecto.\nIncluye:\n✅ Transporte marítimo ida y regreso\n✅ Cóctel de bienvenida\n✅ Almuerzo típico con opciones deliciosas\n✅ Acceso a instalaciones y zonas de descanso\n✅ Actividades como kayak y paddle board\n✅ Botella de agua por persona\n📌 Ideal para:\nFamilias\nParejas\nAmigos que buscan desconectarse y disfrutar la magia del Caribe\n¡Reserva ahora y vive la experiencia que estabas esperando! 🌊🍹` },
  { name: 'SANTA MARTA PLAYA BLANCA + ACUARIO', price: 180000, cost: 140000 },
  { name: 'SUNSET CATAMARÁN FLAMANTE', price: 200000, cost: 160000 },
  { name: 'TOP 3 BORA BORA', price: 510000, cost: 430000 },
  { name: 'TOP 3 ISLAS – Bora Bora | Pao Pao | Islabela', price: 510000, cost: 357000, description: `Vive una experiencia única visitando tres de las mejores islas del Caribe colombiano en un solo día. Este tour te lleva a disfrutar lo mejor de Bora Bora Beach Club, Pao Pao Hotel & Restaurant e Islabela, con paisajes increíbles, gastronomía, confort y actividades inolvidables.\n✨ Incluye:\n🚤 Transporte en lancha rápida\n🗣️ Guía bilingüe\n🌅 Recorrido panorámico por las Islas del Rosario\n🍹 Trago de bienvenida en cada isla\n💧 Agua fresca a bordo\n🍽️ 3 opciones de almuerzo + bebida en Islabela\n⛱️ Espacios disponibles para disfrutar en cada isla\n📍 Punto de encuentro:\nMuelle La Bodeguita – 8:00 a.m.\n⏳ Regreso aproximado: 3:30 p.m.\nReservas garantizadas hasta las 8:20 a.m.\n🔞 Solo adultos (18+)\n📌 No incluye tasa portuaria ni seguro.\n🌊 Tres islas, tres experiencias y un solo día para recordar.` },
  { name: 'TOP 3 ISLAS PRIVADAS', price: 380000, cost: 310000 },
  { name: 'TOUR BAHIA EN BOTE', price: 90000, cost: 55000 },
  { name: 'Tour Islas del Rosario + Barú – Full Day', price: 180000, cost: 125999, description: `Disfruta un día espectacular con este recorrido combinado por Islas del Rosario y Playa Blanca Barú, uno de los planes más completos para quienes desean explorar varias zonas del Caribe colombiano en una sola experiencia.\nEl tour incluye transporte terrestre y marítimo, visita a puntos turísticos emblemáticos, tiempo en playa, almuerzo caribeño y acompañamiento de guía durante toda la jornada.\n✨ Incluye:\n🚌 Recogida en hotel en los sectores:\nBocagrande, Castillo Grande, Laguito, Boquilla, Crespo, Marbella o punto de encuentro.\n🚌 Transporte ida y regreso en bus climatizado hacia Playa Blanca – Barú\n🚤 Transporte en lancha ida y regreso desde Barú hacia Islas del Rosario\n🪶 Parada en San Martín de Pajarales\n(acuífero natural ideal para observación panorámica)\n🐬 Parada en el Oceanario\n(No incluye entrada)\n🍽️ Almuerzo típico caribeño – 4 opciones:\nPollo\nPescado\nCerdo\nVegetariano\n👨✈️ Guía turístico acompañante\n⏰ Horario:\n7:00 a.m. – 3:00 p.m.\n⚠️ Observación:\nOceanario: No incluido\nSnorkel: No incluido\nCarpas y parasoles:  No incluido` },
  { name: 'Tour Playa Tranquila – Isla Barú', price: 170000, cost: 118999, description: `Vive una experiencia personalizada en Playa Tranquila, Barú 🌊✨, perfecta para quienes buscan comodidad, buen servicio y contacto con la naturaleza. Relájate en nuestras asoleadoras 😎, disfruta áreas de descanso 🌴, observa manglares y mapaches 🐾🌿 y sumérgete en una aventura de snorkel entre peces tropicales 🐠🤿. Un plan ideal para desconectar, disfrutar y recibir atención dedicada durante todo el día.\nIncluye:\n🤝 Servicio personalizado\n😎 Asoleadoras y zonas de descanso\n🐾 Avistamiento de manglares y mapaches\n🤿 Snorkel con peces tropicales\n🏝️ Acceso a instalaciones\n🌤️ Áreas sociales y espacios sombreados` },
  { name: 'Tour Punta Arena – Isla Tierra Bomba', price: 80000, cost: 56000, description: `Disfruta un día espectacular en Punta Arena, una de las playas más hermosas y tranquilas de la Isla Tierra Bomba. Este tour es ideal para quienes buscan un ambiente relajado, con aguas claras, arena suave y un clima perfecto para descansar, tomar el sol y desconectarse de la ciudad.\nEl plan incluye transporte marítimo cómodo, almuerzo caribeño y acceso a zonas de descanso diseñadas para una experiencia completa frente al mar.\n✨ Incluye:\n🚤 Transporte ida y vuelta en lancha hacia Punta Arena\n🍽️ Almuerzo típico caribeño – 4 opciones:\nPollo\nPescado\nCerdo\nVegetariano\n🌴 Zonas de descanso:\nSillas\nMesas\n🎵 Música ambiental para disfrutar la playa\n⏰ Horarios de salida:\n8:30 a.m., 9:30 a.m., 10:30 a.m.\n⏰ Horarios de regreso:\n3:30 p.m. y 4:30 p.m.\nNo incluye retorno y gastos no especificados` },
  { name: 'TOUR VOLAR – CARTAGENA DESDE EL CIELO', price: 160000, cost: 112000, description: `⏰ *Horarios*\nMuelle la bodeguita puerta #1\n*Citación:* 9:30 a.m.\n*Salida:* 10:00 a.m.\n*Regreso:* 2:30 p.m.\n🎉 *Incluye:*\n🍸Cóctel de bienvenida\n🕺🏽DJ + show de bailarines\n🍽️Almuerzo tipo buffet:\n- Lomo de cerdo\n- Filete de pescado\n- Pollo Goulash\n*Acompañantes:*\n🥗 Ensalada Fresca\n🍚 Arroz de coco o blanco\n*No incluye bebidas*\n🚁Vuelo panorámico en helicóptero (12 km)\n🚫 No apto para mujeres Embarazadas\n*Impuesto:* 8.000 por persona\nel valor de 160.000 no incluye vuelo panorámico en helicóptero` },
  { name: 'TOURS 5 ISLAS FULL TERRESTRE', price: 250000, cost: 175000, description: `Disfruta un recorrido espectacular por las Islas del Rosario con una experiencia completa llena de actividades, naturaleza, playas hermosas y momentos inolvidables. Ideal para quienes desean aprovechar al máximo el día.\n✨ Incluye:\n🚐 Recogida en hotel\nSectores: Bocagrande, Castillo Grande, Laguito, Boquilla, Crespo, Marbella y Punto de Encuentro hasta Barú.\n🌅 Panorámica Islas del Rosario\n🏖️ Parada en Isla Privada Kokomo\n🤿 Snorkeling\n✈️ Avistamiento avioneta hundida de Pablo Escobar\n🏝️ Visita a Cholón\nIncluye cóctel de mariscos y bohío compartido.\n🌊 Visita Playa Tranquila\nIncluye almuerzo típico, uso de instalaciones y actividades.\n🌇 Atardecer\n✨ Avistamiento de plancton\n⛴️ Retorno\n📌 Nota:\nQuienes deseen entrar al Oceanario deben pagar su entrada directamente en el lugar.\nEl tiempo aproximado de permanencia es de 50 minutos, y quien no ingrese puede disfrutar de la playa o realizar snorkeling.\n⏰ Horario:\n7:00 a.m. – 8:00 p.m.` },
  { name: 'TOURS BAHIA + CLUB DE PLAYA KABANA', price: 200000, cost: 120000, description: `Disfruta de la NOCHE AZUL!  un recorrido en bote deportivo con barra libre de 1:30h por la bahía de Cartagena y continúa en Club Kabanna de 2h o 4h en un espectacular club de playa ubicado en la isla de Tierra Bomba, donde podrás relajarte, disfrutar de un Bar en la playa , un rooftop con piscina frente al mar, y un Restaurante exquisito.\n🚤 La experiencia incluye\n•	🌊 Recorrido de 1:30 h en bote deportivo por la bahía.\n•	🥂 Barra libre durante la navegación: Cuba Libre (ron con Coca-Cola) y Aguardiente con jugo de Naranja.\n•	🎶 Música variada con Animación.\n•	🏝️ Acceso a Club Kabanna isla Tierra Bomba (2-4 horas)\n•	🏊 Uso de playa exclusiva y piscina.\n•	💃 Disco bar entrada incluida.\n•	🥘Cena: Canastas de Patacones con Camarones al Ajillo\nPicada de Chicharrón con Patacones\nPicada de Pollo Apanado con Papas a La Francesa\n📍 Información del tour\n•	Punto de encuentro: Muelle Los Pegasos ( llegar 30 minutos antes)\n•	Hora de salida: 5:00 p.m y 7:00 p.m.\n•	Hora de regreso: 9:00 p.m. y  11:00 p.m` },
  { name: 'TOURS BAHIA BARCO PIRATA', price: 130000, cost: 80000 },
  { name: 'TOURS BAHIA BEQUIA EAGLE', price: 150000, cost: 110000 },
  { name: 'TOURS VOLCAN DEL TOTUMO', price: 170000, cost: 110000 }
]
