export interface ServiceItem {
  name: string
  price: number
  cost: number
  description?: string
}

// Normaliza nombre para comparación: sin tildes, minúsculas, espacios simples
export function normalizeServiceName(s: string): string {
  return (s || '')
    .trim()
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '') // elimina diacríticos/tildes
    .replace(/\s+/g, ' ')            // colapsa espacios múltiples
}

import catalogImages from './catalogImages.json';

export function getTourImages(serviceName: string): string[] {
  const normService = normalizeServiceName(serviceName);
  
  // Custom mappings for tricky names
  const mapping: Record<string, string> = {
    'day pass catamaran bona vida islas del rosario': 'BONA VIDA',
    'city tours barranquilla/santa marta': 'CITY TOURS BARRANQUILLASANTA MARTA',
    'islas del rosario full adventure': 'FULL ADVENTURE',
    'noche blanca bequia': 'NOCHE BLANCA',
    'playa tranquila pack x 4 adventure': 'PACK PLAYA TRANQUILA X 4',
    'sunset catamaran flamante': 'SUNSET CATAMARÁN FLAMANTE',
    'tours bahia + club de playa kabana': 'TOURS BAHIA + KABANA',
    'tours bahia bequia eagle': 'TOURS BAHIA BEQUIA',
    'volcan del totumo': 'TOURS VOLCAN DEL TOTUMO',
    'tour punta arena - isla tierra bomba': 'PUNTA ARENA',
    'palmarito beach vip': 'PALMARITO VIP',
    'tour bahia en bote': 'BOTE RUMBERO',
    'top 3 islas - bora bora | pao pao | islabela': 'NO_EXISTE_PARA_EVITAR_DUPLICADOS'
  };

  let folderName = mapping[normService];

  if (!folderName) {
    // 1. Prioritize exact match
    folderName = Object.keys(catalogImages).find(
      k => normalizeServiceName(k) === normService
    );
  }

  if (!folderName) {
    // 2. If no exact match, try substring match but sort by longest key first
    // to prevent 'BORA BORA' from intercepting 'TOP 3 BORA BORA' if it existed in the name
    const sortedKeys = Object.keys(catalogImages).sort((a, b) => b.length - a.length);
    folderName = sortedKeys.find(
      k => normService.includes(normalizeServiceName(k))
    );
  }

  if (folderName && (catalogImages as Record<string, string[]>)[folderName]) {
    const paths = (catalogImages as Record<string, string[]>)[folderName];
    return Array.from(new Set(paths)).map(p => `/catalog/${p}`);
  }

  return [];
}

export const SERVICES: ServiceItem[] = [
  { name: '4 ISLAS MARITIMO', price: 220000, cost: 150000, description: `¡Descubre el encanto del Archipiélago de Nuestra Señora del Rosario con nuestro tour marítimo por 4 islas! 🌊☀️\nIdeal para quienes desean un tour dinámico lleno de mar, sol y mucha diversión.\n\n✨ Incluye:\n🚤 Transporte: Recorrido en lancha rápida deportiva.\n🏝️ Tour Panorámico: Visita a 4 de las islas más representativas del archipiélago.\n🍽️ Almuerzo Típico: Delicioso plato caribeño frente al mar.\n🤿 Snorkeling: Tiempo dedicado para explorar los arrecifes de coral.\n👨‍✈️ Guía: Acompañamiento durante el recorrido.\n\n📌 Observaciones Importantes:\n• Impuesto portuario no incluido.\n\n⏰ Horario:\n8:00 a.m. – 3:00 p.m.` },
  { name: '5 DESTINOS TERRESTRE', price: 250000, cost: 180000, description: `¡Conoce lo mejor de la región en un solo día con nuestro Tour 5 Destinos Terrestre! 🚌🌴\nExplora 5 hermosos destinos turísticos por vía terrestre en un cómodo bus climatizado. Un recorrido completo para llevarte los mejores recuerdos.\n\n✨ Incluye:\n🚐 Transporte: Bus climatizado ida y regreso.\n🏖️ Recorrido: Visita guiada por 5 hermosos destinos.\n🍽️ Almuerzo Típico: Deliciosa comida local.\n👨‍✈️ Guía Bilingüe: Acompañamiento profesional durante el tour.\n\n📌 Observaciones Importantes:\n• Entradas a atracciones específicas pueden no estar incluidas.\n\n⏰ Horario:\n7:00 a.m. – 5:00 p.m.` },
  { name: '5 ISLAS BASIC', price: 270000, cost: 210000, description: `¡Aventura económica y divertida por 5 islas del archipiélago! 🏝️🚤\nEl plan perfecto para aventureros que desean conocer mucho por un precio increíble.\n\n✨ Incluye:\n🚤 Transporte Marítimo: Lancha rápida ida y regreso.\n🌅 Tour Panorámico: Visita a 5 de las islas más famosas.\n🍽️ Almuerzo Típico: Almuerzo tradicional costeño.\n🤿 Parada para Snorkeling: Explora la vida marina.\n\n📌 Observaciones Importantes:\n• Impuesto portuario no incluido.\n• Actividades extra como el oceanario se pagan en el lugar.\n\n⏰ Horario:\n8:00 a.m. – 3:00 p.m.` },
  { name: '5 ISLAS FULL DAY MARITIMO', price: 280000, cost: 196000, description: `¡Explora lo mejor de las Islas del Rosario en un solo día!\nEste tour está diseñado para quienes quieren vivir una experiencia inolvidable, llena de paisajes espectaculares, playas privadas, actividades acuáticas y momentos únicos en el mar.\nDurante este increíble recorrido disfrutarás de islas paradisíacas, snorkeling, visita a lugares icónicos y el mágico avistamiento del plancton bioluminiscente al caer la noche.\n\n✨ Incluye:\n🚌 Recogida en bus climatizado por la zona hotelera o punto acordado\n🚤 Salida desde muelle asignado\n🏰 Panorámico Fuerte de Bocachica e Islas del Rosario\n🌅 Isla privada Kokomo (50 min)\n🤿 Snorkeling o acuario (30 min)*\n✈️ Avistamiento de avioneta de Pablo Escobar\n🏝️ Visita a Isla Cholón (50 min) con Cóctel de mariscos y Bohío compartido\n🏖️ Playa Tranquila con Almuerzo típico\n🌌 Snack + Avistamiento del plancton bioluminiscente\n🚌 Retorno a Cartagena en bus climatizado\n\n📌 Observaciones Importantes:\n• La visita al acuario no está incluida (valor: $40.000 COP).\n• La actividad de snorkeling dura 50 minutos; si asistes al acuario, pierdes el snorkel.\n\n⏰ Horario:\n7:00 a.m. – 8:00 p.m.` },
  { name: '5 ISLAS OPEN BAR', price: 380000, cost: 300000, description: `¡Vive la mejor fiesta en el mar Caribe con nuestro tour 5 Islas Open Bar! 🍹🎶\nMúsica, sol, playa y barra libre a bordo para que disfrutes al máximo con tus amigos.\n\n✨ Incluye:\n🚤 Transporte: Lancha rápida o yate deportivo.\n🍹 Barra Libre a Bordo: Bebidas y cócteles ilimitados durante el recorrido.\n🏝️ Visitas: Recorrido panorámico y paradas en 5 islas icónicas.\n🍽️ Almuerzo Típico: Deliciosa comida costeña frente al mar.\n🎵 Entretenimiento: Música y ambiente de fiesta.\n\n📌 Observaciones Importantes:\n• Sólo para mayores de edad (18+).\n• Impuesto de muelle no incluido.\n\n⏰ Horario:\n8:30 a.m. – 3:00 p.m.` },
  { name: '5 ISLAS PREMIUM OPEN BAR', price: 380000, cost: 266000, description: `¡Vive la aventura náutica más completa en Cartagena!\nDisfruta un recorrido inolvidable por las aguas cristalinas del Caribe, explorando las Islas del Rosario y lugares icónicos como Cholon y Barú. ¡Ideal para celebrar momentos únicos como cumpleaños o pedidas de mano!\n\n✨ Incluye:\n🗣️ Guía orientador en inglés y español.\n🏨 Recogida en hotel desde las 7:30 a.m.\n🚤 Bote deportivo y Zarpe 9:00 a.m. desde marina privada.\n🏝️ Vista panorámica de las 28 Islas del Rosario y Fortalezas.\n🤿 Snorkeling en arrecifes coralinos y en la avioneta sumergida.\n🏝️ Parada en Isla Cholon y en Isla Agua Azul.\n🍽️ Parada en Playa Tranquila (Isla Barú) con almuerzo incluido.\n🎉 Decoración especial para cumpleaños y pedidas de mano.\n🍻 OPEN BAR a bordo: cervezas, gaseosas y agua (hasta agotar existencia).\n\n📌 Observaciones Importantes:\n• Retorno 3:00 p.m. al muelle Bodeguita (no incluye retorno al hotel).\n• Incluye impuesto de muelle.\n\n⏰ Horario:\n7:30 a.m. – 3:00 p.m.` },
  { name: '5 ISLAS VIP + PLANTON', price: 380000, cost: 300000, description: `Experiencia premium por 5 islas con comodidades VIP, y un cierre mágico al atardecer observando el plancton bioluminiscente.\n\n✨ Incluye:\n🚤 Transporte VIP en lancha rápida.\n🏝️ Visita a 5 islas exclusivas.\n🍽️ Almuerzo Premium: Deliciosa gastronomía local.\n🌌 Avistamiento de Plancton: Cierra tu día nadando en aguas bioluminiscentes.\n⛴️ Retorno seguro.\n\n📌 Observaciones Importantes:\n• Tasa portuaria no incluida.\n\n⏰ Horario:\n8:00 a.m. – 8:00 p.m.` },
  { name: 'ATARDECER EN CATAMARAN SAN JUAN', price: 180000, cost: 125999, description: `¡Un espectacular atardecer a bordo de un catamarán! Disfruta de vistas increíbles, buena música y barra libre.\n\n✨ Incluye:\n🚢 2 horas de recorrido por la bahía interna de Cartagena.\n🍹 2 bebidas por persona de bienvenida.\n🥟 Pasabocas (mini fritos típicos).\n🍸 Barra libre en cócteles con y sin alcohol.\n🎧 DJ en vivo + animación.\n\n📌 Observaciones Importantes:\n• No incluye: tasa portuaria 18.000 COP por persona (debe pagarse en efectivo).\n\n⏰ Horario:\nEncuentro: 5:00 pm – Muelle de la Bodeguita puerta N°4.\nZarpe: 5:30 pm | Regreso: 7:30 pm.` },
  { name: 'ATOLON BEACH CLUB', price: 350000, cost: 300000, description: `¡Un día de lujo en Atolón Beach Club! 🏖️🍹\nPasadía exclusivo con instalaciones de primer nivel, gastronomía excepcional y una playa tranquila para relajarte.\n\n✨ Incluye:\n🚤 Transporte: Ida y vuelta en lancha rápida.\n🍹 Cóctel de Bienvenida: Bebida refrescante al llegar.\n🍽️ Almuerzo: Opciones a la carta para deleitar tu paladar.\n🏖️ Instalaciones: Uso de asoleadoras, camas de playa y duchas.\n🎵 Ambiente: Música relajante y excelente atención.\n\n📌 Observaciones Importantes:\n• No incluye tasa portuaria.\n\n⏰ Horario:\n8:00 a.m. – 3:00 p.m.` },
  { name: 'AVIARIO + BARU', price: 160000, cost: 90000, description: `¡Conexión total con la naturaleza y el mar! 🦜🌊\nDisfruta del majestuoso Aviario Nacional y luego relájate en las cálidas aguas de Barú.\n\n✨ Incluye:\n🚐 Transporte: Bus climatizado ida y regreso.\n🏖️ Playa: Tiempo de relajación en Playa Blanca, Barú.\n🍽️ Almuerzo Típico: Delicioso plato caribeño.\n👨‍✈️ Guía Acompañante.\n\n📌 Observaciones Importantes:\n• NO incluye la entrada al Aviario Nacional de Colombia.\n• No incluye carpas ni parasoles en la playa.\n\n⏰ Horario:\n7:00 a.m. – 3:00 p.m.` },
  { name: 'BARU + ISLAS DEL ROSARIO TERRESTRE', price: 180000, cost: 110000, description: `¡Lo mejor de dos mundos en un solo tour! 🌴🚌\nUn tour combinado espectacular. Recorre en bus hacia Barú y luego toma una lancha hacia las hermosas Islas del Rosario.\n\n✨ Incluye:\n🚐 Transporte Terrestre: Bus climatizado hasta la península de Barú.\n🚤 Transporte Marítimo: Lancha hacia las Islas del Rosario.\n🌅 Tour Panorámico: Recorrido por el archipiélago.\n🍽️ Almuerzo Típico: Comida costeña en Barú.\n🏖️ Tiempo Libre: Descanso en la playa.\n\n📌 Observaciones Importantes:\n• Oceanario no incluido.\n\n⏰ Horario:\n7:00 a.m. – 3:00 p.m.` },
  { name: 'BORA BORA BEACH CLUB', price: 390000, cost: 310000, description: `¡Exclusividad y buen ambiente en Bora Bora Beach Club! 🎶🌴\nDisfruta de un entorno vibrante, buena música y camas asoleadoras en uno de los clubes de playa más famosos.\n\n✨ Incluye:\n🚤 Transporte: Lancha rápida ida y regreso.\n🍹 Cóctel de Bienvenida: Refrescante bebida a tu llegada.\n🍽️ Almuerzo Típico: Delicioso plato caribeño.\n🏖️ Comodidades: Uso de asoleadora o cama de playa.\n🎧 Ambiente: DJ en vivo y el mejor estilo chillout.\n\n📌 Observaciones Importantes:\n• Impuesto portuario no incluido.\n• Prohibido el ingreso de alimentos y bebidas.\n\n⏰ Horario:\n8:00 a.m. – 3:00 p.m.` },
  { name: 'BORA BORA BEACH VIP', price: 490000, cost: 420000, description: `¡La experiencia más premium del Caribe en Bora Bora VIP! 💎🍾\nCama balinesa en primera fila, atención VIP y el mejor ambiente chillout del Caribe.\n\n✨ Incluye:\n🚤 Transporte: Lancha rápida de lujo.\n🍹 Cóctel de Bienvenida VIP.\n🍽️ Almuerzo a la Carta: Exquisita gastronomía.\n🏖️ Zona VIP: Cama balinesa en primera fila garantizada.\n💁‍♂️ Atención Personalizada.\n\n📌 Observaciones Importantes:\n• Impuesto portuario no incluido.\n• Exclusivo para adultos.\n\n⏰ Horario:\n8:00 a.m. – 3:00 p.m.` },
  { name: 'BUCEO EN BARU', price: 330000, cost: 250000, description: `¡Descubre el mundo submarino del Caribe en Barú! 🤿🐠\nSumérgete en aguas cristalinas y descubre la increíble vida marina del Caribe colombiano.\n\n✨ Incluye:\n🚐 Transporte: Terrestre o marítimo hasta la zona de inmersión.\n🤿 Equipamiento: Equipo de buceo completo (traje, tanque, aletas, máscara).\n👨‍🏫 Instrucción: Inmersión con instructor certificado (PADI/NAUI).\n📸 Fotografías Acuáticas.\n🍽️ Almuerzo Típico.\n\n📌 Observaciones Importantes:\n• No se requiere experiencia previa.\n• No apto para personas con afecciones respiratorias graves o mujeres embarazadas.\n\n⏰ Horario:\n7:00 a.m. – 3:00 p.m.` },
  { name: 'CATAMARAN SAN JUAN', price: 180000, cost: 120000, description: `¡Navega con estilo a bordo del Catamarán San Juan! ⛵🌅\nUn divertido pasadía de navegación suave, paradas para bañarse en el mar y barra de bebidas.\n\n✨ Incluye:\n⛵ Transporte: Navegación en catamarán espacioso.\n🍹 Bebidas: Barra libre de bebidas no alcohólicas.\n🏖️ Paradas para Baño: Tiempo para sumergirse en aguas cristalinas.\n🍽️ Almuerzo a Bordo: Comida preparada fresca.\n🤿 Equipo de Snorkel incluido.\n\n📌 Observaciones Importantes:\n• Tasa portuaria no incluida.\n\n⏰ Horario:\n8:30 a.m. – 4:30 p.m.` },
  { name: 'CHIVA RUMBERA', price: 50000, cost: 30000, description: `¡Embárcate en una experiencia inolvidable a bordo de la Chiva Rumbera!\nDescubre la magia nocturna de Cartagena mientras recorres sus lugares más emblemáticos en un ambiente lleno de música.\n\n✨ Incluye:\n🚌 Recorrido por Bocagrande, Torre del Reloj, Muelle de los Pegasos.\n🏰 Recorrido panorámico por las murallas de Cartagena.\n🎶 Animador/DJ a bordo.\n📸 Paradas de 10 minutos para tomar fotografías.\n🚏 Recogida en puntos de encuentro autorizados.\n\n📌 Observaciones Importantes:\n• No incluye bebidas ni comida (puedes llevar las tuyas).\n\n⏰ Horario:\n07:00 pm – 09:00 pm (o 09:15 pm - 11:00 pm).` },
  { name: 'CITY TOUR PERSONALIZADO EN CARTAGENA', price: 280000, cost: 196000, description: `¡Descubre la historia y el encanto de Cartagena con la comodidad que mereces!\nEste recorrido está diseñado para grupos pequeños de hasta 4 personas.\n\n✨ Incluye:\n✅ Recorrido panorámico por: Castillo San Felipe, Convento de la Popa, Getsemaní, Manga.\n✅ Opción de visitar otros sitios a elección.\n✅ Transporte climatizado tipo Uber o taxi driver.\n✅ Botella de agua por persona.\n\n📌 Observaciones Importantes:\n• Duración: 3 horas.\n• Las entradas a los sitios turísticos no están incluidas.\n\n⏰ Horario:\nFlexible, a convenir.` },
  { name: 'CITY TOURS BARRANQUILLA/SANTA MARTA', price: 280000, cost: 210000, description: `¡Conoce las joyas del Caribe colombiano en un solo día! 🚌🌆\nExcursión completa desde Cartagena para conocer la Puerta de Oro de Colombia (Barranquilla) y la magia de Santa Marta.\n\n✨ Incluye:\n🚐 Transporte: Bus climatizado ida y regreso desde Cartagena.\n📸 Paradas en Barranquilla: Monumento Ventana al Mundo, Aleta del Tiburón.\n🏖️ Paradas en Santa Marta: Visita al Rodadero, Quinta de San Pedro Alejandrino.\n🍽️ Desayuno y Almuerzo: Alimentación completa incluida.\n👨‍✈️ Guía Profesional.\n\n📌 Observaciones Importantes:\n• El viaje es extenso (aprox 2.5 a 3 horas de trayecto por trayecto).\n\n⏰ Horario:\n4:00 a.m. – 9:00 p.m.` },
  { name: 'CITY TOURS CARTAGENA EN CHIVA', price: 90000, cost: 62999, description: `¡Descubre Cartagena como nunca antes!\nEmbárcate en nuestro City Tour en Chiva Turística, el transporte típico y colorido que te conecta con la esencia caribeña.\n\n✨ Incluye:\n📸 Paradas fotográficas en la Bahía, las Botas Viejas y letras de Cartagena.\n🏰 Visita al Castillo de San Felipe y la histórica Iglesia San Pedro Claver.\n👣 Caminata guiada por el Centro Histórico.\n👨‍✈️ Guía profesional turístico.\n\n📌 Observaciones Importantes:\n• Bebidas y alimentación no incluidas.\n\n⏰ Horario:\nFlexibles: 9:00 a.m. - 1:00 p.m. | 2:00 p.m. - 6:00 p.m.` },
  { name: 'CITY TOURS LITE', price: 90000, cost: 60000, description: `¡Lo indispensable de Cartagena de forma rápida y económica! 🏰📸\nEl recorrido ideal para conocer la historia y la magia de la ciudad amurallada.\n\n✨ Incluye:\n🚐 Transporte: Recorrido en bus o minivan climatizada.\n🏰 Castillo de San Felipe: Parada para fotografías (sin ingreso).\n🥾 Zapatos Viejos: Visita al emblemático monumento.\n🚶‍♂️ Ciudad Amurallada: Caminata guiada por las principales calles del Centro Histórico.\n👨‍✈️ Guía Certificado.\n\n📌 Observaciones Importantes:\n• No incluye entradas a los monumentos.\n\n⏰ Horario:\n2:00 p.m. – 6:00 p.m.` },
  { name: 'CITY TOURS PALENQUE', price: 345000, cost: 300000, description: `¡Sumérgete en la cultura afrocolombiana ancestral! 🥁🏿\nVisita San Basilio de Palenque, el primer pueblo libre de América.\n\n✨ Incluye:\n🚐 Transporte: Bus climatizado ida y regreso.\n🗣️ Guía Local Palenquero.\n🎶 Muestra Cultural: Presentación de tambores y danza típica.\n🍽️ Almuerzo Tradicional: Gastronomía ancestral palenquera.\n📸 Recorrido: Visita a la plaza principal, monumento y encuentro con las palenqueras.\n\n📌 Observaciones Importantes:\n• Se recomienda llevar dinero en efectivo para comprar artesanías y dulces típicos.\n\n⏰ Horario:\n8:00 a.m. – 3:00 p.m.` },
  { name: 'CITY TOURS PERSONALIZADO X4', price: 280000, cost: 200000, description: `¡Descubre Cartagena a tu propio ritmo! 🚙🏰\nTour diseñado especialmente para grupos pequeños de hasta 4 personas con conductor y guía privado.\n\n✨ Incluye:\n🚗 Transporte Privado: Vehículo climatizado exclusivo.\n👨‍✈️ Conductor y Guía: Atención 100% personalizada.\n📍 Itinerario Flexible: Tú decides dónde ir.\n💧 Bebidas: Aguas embotelladas para el grupo.\n\n📌 Observaciones Importantes:\n• No incluye el costo de las entradas a los monumentos.\n• Duración máxima de 4 horas.\n\n⏰ Horario:\nA convenir por el cliente.` },
  { name: 'CITY TOURS PREMIUM GRUPAL', price: 1100000, cost: 950000, description: `¡La magia de Cartagena con el mayor confort! 🌟🚌\nDescubre la historia de la ciudad heroica con transporte de lujo, guía bilingüe y acceso a los sitios históricos más emblemáticos.\n\n✨ Incluye:\n🚐 Transporte Premium: Bus o minivan de lujo climatizado.\n🎫 Entradas Incluidas: Ingreso al Castillo de San Felipe y al Convento de la Popa.\n🚶‍♂️ Caminata Guiada: Recorrido por el Centro Histórico y Barrio Getsemaní.\n🍹 Refrigerio: Hidratación y snack típico local.\n👨‍✈️ Guía Bilingüe.\n\n📌 Observaciones Importantes:\n• Ideal para grupos grandes que buscan un servicio todo incluido.\n\n⏰ Horario:\n2:00 p.m. – 6:00 p.m.` },
  { name: 'DAY PASS CATAMARAN BONA VIDA ISLAS DEL ROSARIO', price: 430000, cost: 301000, description: `Pasadía a Islas del Rosario en Catamarán Bonavida:⚓🛥️💙\nEmbárcate en una experiencia inolvidable navegando en un catamarán de lujo desde Cartagena hacia las Islas del Rosario.\n\n✨ Incluye:\n🛥️ Transporte: Catamarán de lujo hacia Isla Grande y Punta Gigante.\n🍹 Cóctel de bienvenida y Bebidas no alcohólicas.\n🍢 Snacks y Aperitivos (empanaditas, quibbe, deditos de queso).\n🍽️ Almuerzo a Bordo.\n🤿 Snorkeling: Máscara y tubo gratuito.\n💰 Impuestos Incluidos: Tasa de embarque y Tasa entrada PNN.\n\n📌 Observaciones Importantes:\n• Está prohibido el ingreso de alimentos o bebidas al catamarán.\n\n⏰ Horario:\nEmbarque: 8:00 A.M. en Muelle la Bodeguita (Zarpe: 8:30 A.M.).` },
  { name: 'DAYPASS PLAYA BLANCA BARU', price: 100000, cost: 70000, description: `Disfruta un día espectacular en Playa Blanca Barú, una de las playas más hermosas del Caribe colombiano.\n\n✨ Incluye:\n🚌 Recogida en hotel.\n🚐 Transporte ida y vuelta en bus climatizado hasta Barú.\n🍽️ Almuerzo típico caribeño (4 opciones: Pollo, Pescado, Cerdo, Vegetariano).\n👨‍✈️ Guía turístico acompañante.\n🏖️ Día libre para disfrutar del mar.\n\n📌 Observaciones Importantes:\n• No incluye carpas y parasoles (se adquieren directamente en la playa).\n\n⏰ Horario:\n7:00 a.m. – 3:00 p.m.` },
  { name: 'ETEKA BEACH CLUB', price: 300000, cost: 260000, description: `¡Escápate a la tranquilidad del paraíso!\nA solo 10 minutos en lancha desde Cartagena, disfruta un día lleno de relax y diversión en un entorno natural y exclusivo en Isla Tierra Bomba.\n\n✨ Incluye:\n🚤 Transporte en lancha (ida y regreso)\n🍹 Cóctel de bienvenida\n🏖️ Acceso a 2 playas y piscina\n🍽️ Almuerzo de 2 tiempos (plato fuerte y postre) con opciones variadas\n🎶 DJ en vivo los sábados y ambientes musicales\n\n📌 Observaciones Importantes:\n• Ideal para desconectarse cerca a la ciudad sin viajes largos.\n\n⏰ Horario:\n9:00 a.m. – 3:00 p.m.` },
  { name: 'HELICOPTERO CARTAGENA', price: 420000, cost: 350000, description: `¡La experiencia más premium de Cartagena desde el cielo! 🚁☁️\nSobrevuela Cartagena de Indias en un helicóptero privado y captura las mejores vistas de las fortificaciones y el mar.\n\n✨ Incluye:\n🚁 Vuelo Privado: Sobrevuelo panorámico de 12 a 15 minutos en helicóptero.\n🏙️ Ruta Exclusiva: Vistas del Centro Histórico, Castillo San Felipe, Bahía, Bocagrande y Tierrabomba.\n🥂 Brindis VIP: Copa de champaña antes o después del vuelo.\n🚐 Traslado: Transporte ida y vuelta al helipuerto.\n\n📌 Observaciones Importantes:\n• Capacidad sujeta al peso de los pasajeros y modelo de la aeronave.\n\n⏰ Horario:\nVuelos disponibles entre 9:00 a.m. y 4:30 p.m.` },
  { name: 'IBBIZA BEACH', price: 370000, cost: 300000, description: `¡Haz una pausa y regálate un día de lujo en IBBIZA Island Beach Club!\nSumérgete en un ambiente exclusivo donde el confort, la buena vibra y la belleza natural del Caribe se combinan.\n\n✨ Incluye:\n🚤 Transporte: Traslado en lancha ida y regreso.\n🏖️ Acceso: Instalaciones exclusivas del beach club (camas y sillas asoleadoras).\n🏊‍♀️ Piscina con vista al mar.\n🍹 Cóctel de bienvenida.\n🍽️ Almuerzo tipo gourmet según menú del día.\n🎶 Música ambiente y atención personalizada.\n\n📌 Observaciones Importantes:\n• Perfecto para parejas o grupos de amigos que buscan un día de lujo.\n\n⏰ Horario:\n8:30 a.m. – 3:00 p.m.` },
  { name: 'ISLA PALMA', price: 495000, cost: 420000, description: `¡Disfruta de la reserva natural de Isla Palma en San Bernardo! 🌴🐾\nArena blanca, aguas cristalinas y un bio-parque lleno de sorpresas naturales.\n\n✨ Incluye:\n🚐 Traslado: Desde el hotel hasta el muelle.\n🚤 Navegación: Recorrido panorámico por Islas del Rosario y Archipiélago de San Bernardo.\n🍹 Snack de frutas y Coctel de bienvenida.\n🏝️ Acceso exclusivo al Hotel Isla Palma (Reserva Natural).\n🍽️ Almuerzo gourmet: Proteína a elección, barra de ensaladas, jugo y postre.\n🏖️ Tiempo libre: Playa de arena blanca y aguas cristalinas.\n\n📌 Observaciones Importantes:\n• No incluye Tasa portuaria ($37.000 COP por persona).\n• Visita opcional al BioParque (costo adicional $20.000 COP).\n\n⏰ Horario:\nMuelle La Bodeguita (5:45 a.m.). Retorno aproximado 5:00 p.m.` },
  { name: 'ISLABELA BEACH', price: 420000, cost: 360000, description: `¡Pasadía de descanso total en Islabela! 🌴✨\nUna playa paradisíaca en las Islas del Rosario donde podrás disfrutar de un mar turquesa y un almuerzo espectacular.\n\n✨ Incluye:\n🚤 Transporte: Lancha ida y regreso desde Cartagena.\n🍹 Cóctel de Bienvenida: Bebida especial de bienvenida.\n🏖️ Asoleadora: Uso garantizado de camas o sillas asoleadoras.\n🍽️ Almuerzo Excepcional: Gastronomía caribeña de alta calidad.\n🏄 Actividades: Uso de Paddle board y Kayaks sujeto a disponibilidad.\n\n📌 Observaciones Importantes:\n• Impuesto de muelle no incluido.\n• Excelente ambiente ecoturístico.\n\n⏰ Horario:\n8:00 a.m. – 3:00 p.m.` },
  { name: 'ISLAS DEL ROSARIO + PLAYA BLANCA BARU MARITIMO', price: 170000, cost: 118999, description: `¡Dos de los destinos más apetecidos del Caribe en un solo día! 🚤🌊\n\n✨ Incluye:\n🚐 Recogida en hotel (sector Bocagrande, Laguito, Castillo Grande).\n🚤 Recorrido en lancha por el archipiélago.\n🐬 Visita isla San Martín de Pajarales (opcional ingreso al Oceanario o Snorkeling).\n🏝️ Visita Isla Barú - Playa Blanca.\n🍽️ Almuerzo típico (pollo, pescado o vegetariano).\n👨‍✈️ Guía acompañante.\n\n📌 Observaciones Importantes:\n• No incluye Impuesto Turístico.\n• No incluye Retorno al hotel (el tour termina en el muelle).\n• Actividades de Snorkeling ($50.000) y Oceanario ($40.000) tienen costo adicional.\n\n⏰ Horario:\n8:00 a.m. – 3:00 p.m.` },
  { name: 'ISLAS DEL ROSARIO FULL ADVENTURE', price: 270000, cost: 190000, description: `¡Tour Islas del Rosario - Full Adventure! 🌴☀️\nVive un día inolvidable en el paraíso. Disfruta de una experiencia completa explorando la belleza de Cartagena y sus islas.\n\n✨ Incluye:\n🚐 Transporte: Recogida en la zona hotelera.\n🏝️ Destinos: Visita a Isla Barú (Playa Blanca) y recorrido panorámico por Islas del Rosario.\n🐬 Oceanario: Entrada INCLUIDA (estancia de 1h 30min).\n🤿 Snorkel: Explora los arrecifes de coral (incluye fotos acuáticas).\n🦝 Naturaleza: Avistamiento de mapaches (incluye fotos).\n🍽️ Almuerzo: Deliciosa comida en Playa Blanca con mesa reservada.\n\n📌 Observaciones Importantes:\n• Una de las pocas opciones que incluye el costo del Oceanario y del Snorkel.\n\n⏰ Horario:\n07:00 a.m. – 04:30 p.m.` },
  { name: 'ISLAS DEL ROSARIO MARITIMO', price: 160000, cost: 120000, description: `¡El clásico y espectacular viaje a las Islas del Rosario! 🚤🌴\nViaje en lancha rápida recorriendo panorámicamente el archipiélago, con opciones de snorkeling y visita al oceanario.\n\n✨ Incluye:\n🚤 Transporte: Lancha rápida ida y regreso desde Cartagena.\n🌅 Tour Panorámico: Recorrido por las 27 islas del archipiélago.\n🏝️ Parada en Isla: Tiempo para disfrutar del mar y la playa.\n🍽️ Almuerzo Típico: Plato de pescado frito, arroz con coco, patacones y ensalada.\n👨‍✈️ Guía Acompañante: Asistencia en el trayecto.\n\n📌 Observaciones Importantes:\n• Entradas al Oceanario y equipo de Snorkeling no incluidos.\n• Tasa portuaria (Impuesto de muelle) no incluida.\n\n⏰ Horario:\n8:30 a.m. – 3:00 p.m.` },
  { name: 'LUXURY AMBIENTE VIP', price: 490000, cost: 410000, description: `Vive un día exclusivo en el paraíso con servicio premium, comodidad total y un ambiente vibrante frente al mar.\n\n✨ Incluye:\n🚤 Transporte ida y vuelta en lancha TRITÓN.\n🍷 Copa de vino de bienvenida.\n🍹 Barra Abierta Ilimitada (Bebida Nacional): Coctelería premium, cerveza, gaseosa.\n🛏️ Servicio DIRECTO a la cama y en la barra.\n🎧 DJ en vivo todos los días.\n🍽️ 10 Opciones de almuerzo a la carta.\n🏖️ Cama de playa (por pareja).\n\n📌 Observaciones Importantes:\n• OPCIONAL: Tour panorámico Islas del Rosario o traslado al Oceanario. (Entrada no incluida).\n• Ambiente musical para mayores de 10 años.\n• Impuesto portuario no incluido.\n\n⏰ Horario:\n8:00 a.m. – 3:00 p.m.` },
  { name: 'LUXURY BEACH', price: 430000, cost: 370000, description: `¡Una experiencia de lujo total con Barra Libre! 💎🍹\n\n✨ Incluye:\n🚤 Transporte en Lancha TRITÓN (ida y vuelta).\n🍹 Barra Abierta Ilimitada: Margaritas, Cuba Libre, Mojitos, Cerveza del día, agua y gaseosa.\n🍽️ 4 Opciones de Almuerzo a Elegir (Pesca a la plancha, Pollo, Arroz de mariscos, Arroz con vegetales).\n🏖️ Comodidad en la Playa: Parasol y asoleadora playera individuales.\n🚿 Ducha de Agua Dulce.\n\n📌 Observaciones Importantes:\n• Opcional: Tour panorámico por Islas del Rosario o traslado al Oceanario (Entrada no incluida).\n• Impuesto portuario no incluido.\n\n⏰ Horario:\n8:00 a.m. – 3:00 p.m.` },
  { name: 'MANGATA BEACH', price: 420000, cost: 360000, description: `¡Vive un día inolvidable en Mangata Beach! 🌴🐚\nArena blanca, mar cristalino y una propuesta gastronómica exquisita para disfrutar al máximo.\n\n✨ Incluye:\n🚤 Transporte: Lancha rápida ida y regreso.\n🍹 Bienvenida: Cóctel refrescante al llegar a la isla.\n🍽️ Almuerzo Especial: Opciones gastronómicas de alto nivel frente al mar.\n🏖️ Instalaciones: Uso de sillas asoleadoras, hamacas y zonas de descanso.\n🎶 Ambiente: Música y exclusividad garantizada.\n\n📌 Observaciones Importantes:\n• Impuesto portuario no incluido.\n\n⏰ Horario:\n8:00 a.m. – 3:00 p.m.` },
  { name: 'MANTAS BEACH', price: 400000, cost: 330000, description: `Disfruta un día exclusivo en Mantas Beach, ubicado en la paradisíaca Isla Grande, con playa de arena blanca y aguas cristalinas.\n\n✨ Incluye:\n🚤 Transporte en lancha rápida ida y vuelta.\n🥂 Copa de champaña o limonada de bienvenida.\n🍽️ Almuerzo a la carta (8 opciones con bebida).\n🛌 Asoleadora.\n🏄 Actividades acuáticas: Paddleboards y kayaks.\n🚿 Duchas de agua dulce.\n🎶 DJ’s en vivo todos los días.\n\n📌 Observaciones Importantes:\n• No incluye: tarifa administrativa (muelle), entrada al Oceanario, servicio de toallas.\n\n⏰ Horario:\nSalida: 7:30 a.m. desde Muelle Todomar. Regreso aproximado: 3:00 p.m.` },
  { name: 'MARGARITA BEACH', price: 180000, cost: 130000, description: `¡Un espacio diseñado para el descanso y la tranquilidad familiar! 🏖️🍹\nDisfruta de un día de playa clásico con deliciosa comida caribeña en Margarita Beach, Isla Tierra Bomba.\n\n✨ Incluye:\n🚤 Transporte: Traslado corto en lancha (10 min).\n🍹 Cóctel de Bienvenida: Bebida refrescante.\n🍽️ Almuerzo Típico: Opciones deliciosas de comida local.\n🏖️ Instalaciones: Uso de carpas, sillas asoleadoras y piscina (si aplica).\n🎵 Ambiente Familiar: Ideal para relajarse lejos del bullicio.\n\n📌 Observaciones Importantes:\n• No incluye bebidas adicionales.\n\n⏰ Horario:\n9:00 a.m. – 3:00 p.m.` },
  { name: 'NOCHE BLANCA BEQUIA', price: 300000, cost: 240000, description: `¡Una noche mágica navegando por la hermosa bahía de Cartagena! 🚢✨\nCódigo de vestimenta blanco, cena especial, música en vivo y vistas espectaculares de la ciudad iluminada.\n\n✨ Incluye:\n🚢 Navegación: Recorrido en la embarcación Bequia por la bahía interna.\n👗 Dress Code: Noche de blanco (recomendado).\n🍽️ Cena Especial: Menú servido a bordo a tres tiempos.\n🍷 Bebidas: Copa de vino para brindar y bebidas no alcohólicas.\n🎵 Entretenimiento: Música en vivo y pista de baile.\n\n📌 Observaciones Importantes:\n• Tasa portuaria no incluida.\n• Ideal para celebraciones románticas y aniversarios.\n\n⏰ Horario:\n7:00 p.m. – 10:00 p.m.` },
  { name: 'PALMARITO BEACH', price: 260000, cost: 200000, description: `¡Pasadía perfecto a pocos minutos de la ciudad! 🏝️👙\nCruza a Isla Tierra Bomba y disfruta de piscinas, acceso a la playa y un gran almuerzo tipo buffet.\n\n✨ Incluye:\n🚤 Transporte: Lancha rápida (10-15 minutos).\n🍹 Bienvenida: Bebida refrescante.\n🍽️ Almuerzo Buffet: Variedad de comida caribeña e internacional.\n🏊‍♂️ Instalaciones: Uso de piscinas, asoleadoras, hamacas y playa privada.\n🏐 Actividades: Cancha de voleibol y deportes de playa.\n\n📌 Observaciones Importantes:\n• Tasa portuaria y bebidas adicionales no incluidas.\n\n⏰ Horario:\n9:00 a.m. – 3:00 p.m.` },
  { name: 'PALMARITO BEACH VIP', price: 340000, cost: 280000, description: `¡Confort superior y exclusividad en Palmarito Beach VIP! 🥂🌴\nMejora tu experiencia con acceso a zonas exclusivas, bebidas especiales y un confort superior.\n\n✨ Incluye:\n🚤 Transporte: Traslado en lancha ida y regreso.\n🥂 Bebida Premium: Cóctel o bebida especial de bienvenida.\n🍽️ Almuerzo VIP: Menú a la carta con opciones premium.\n🏖️ Zona Exclusiva: Acceso a camas balinesas o zona reservada.\n🏊‍♂️ Instalaciones: Uso libre de piscinas y playa.\n💁‍♀️ Servicio: Atención preferencial y toallas incluidas.\n\n📌 Observaciones Importantes:\n• Tasa portuaria no incluida.\n\n⏰ Horario:\n9:00 a.m. – 3:00 p.m.` },
  { name: 'PAO PAO BEACH CLUB', price: 390000, cost: 310000, description: `¡Siente la buena energía y la exclusividad en Pao Pao Beach Club! 🦩🎵\nDos piscinas, música de DJs, diseño espectacular y el ambiente perfecto para celebrar en las Islas del Rosario.\n\n✨ Incluye:\n🚤 Transporte: Lancha rápida deportiva.\n🍹 Cóctel de Bienvenida: Bebida de cortesía al llegar.\n🍽️ Almuerzo Exquisito: Variedad de platos gourmet caribeños a la carta.\n🏖️ Instalaciones: Uso de asoleadoras, acceso al mar y a las piscinas de agua dulce.\n🎧 Ambiente: Música electrónica / chillout con DJ residente.\n\n📌 Observaciones Importantes:\n• Solo adultos (18+).\n• Impuesto de muelle no incluido.\n• Camas balinesas pueden requerir consumo mínimo adicional.\n\n⏰ Horario:\n8:00 a.m. – 3:00 p.m.` },
  { name: 'PASADIA PLAYA BLANCA', price: 100000, cost: 60000, description: `¡Un día de arena blanca y aguas turquesas en Barú! 🚌🏖️\nDisfruta de un día completo de mar y sol en la famosa Playa Blanca, con transporte en bus y un tradicional almuerzo costeño.\n\n✨ Incluye:\n🚐 Transporte: Bus climatizado ida y regreso desde la ciudad.\n🏖️ Tiempo Libre: Disfrute de la hermosa Playa Blanca, Barú.\n🍽️ Almuerzo Típico: Pescado, pollo o vegetariano con arroz de coco.\n👨‍✈️ Guía Acompañante: Orientación durante el recorrido.\n\n📌 Observaciones Importantes:\n• No incluye alquiler de carpas o sillas asoleadoras (se negocian directamente).\n• Fuerte presencia de vendedores locales.\n\n⏰ Horario:\n7:00 a.m. – 3:00 p.m.` },
  { name: 'PASADIA PLAYA TRANQUILA', price: 170000, cost: 95000, description: `¡Escápate a un sector exclusivo y más calmado en Barú! 🌴🧘‍♀️\nComo su nombre lo indica, es el lugar ideal para relajarse lejos del ruido y las multitudes.\n\n✨ Incluye:\n🚐 Transporte Terrestre: Bus climatizado hasta Barú.\n🚤 Traslado Marítimo Corto: Lancha hasta el sector de Playa Tranquila.\n🍹 Bebida: Refresco de bienvenida.\n🏖️ Instalaciones: Uso de sillas asoleadoras y sombrillas en zona privada.\n🍽️ Almuerzo Típico: Delicioso plato caribeño.\n\n📌 Observaciones Importantes:\n• Sector con mucha menos afluencia de vendedores.\n\n⏰ Horario:\n7:00 a.m. – 3:00 p.m.` },
  { name: 'PASADIA PUNTA ARENA', price: 80000, cost: 50000, description: `¡Cruza a Tierra Bomba en 10 minutos y disfruta de Punta Arena! 🚤⛱️\nExcelente vista de la zona moderna de Cartagena (Bocagrande) mientras descansas en una playa de arena blanca.\n\n✨ Incluye:\n🚤 Transporte: Lancha ida y regreso desde Castillogrande o el Hospital de Bocagrande.\n🍽️ Almuerzo Típico: Pescado frito o pollo con patacones y arroz.\n🏖️ Instalaciones: Uso de sillas y sombrillas básicas.\n🎶 Ambiente: Música caribeña y aguas tranquilas.\n\n📌 Observaciones Importantes:\n• Ideal para un plan de medio día o de presupuesto ajustado.\n\n⏰ Horario:\nSalidas flexibles desde las 9:00 a.m. y retornos hasta las 3:00 p.m.` },
  { name: 'PAUE BEACH', price: 470000, cost: 380000, description: `¡Vive un día de ensueño en las Islas del Rosario! 🌴✨\nEscápate a un paraíso natural y disfruta de una experiencia única frente al mar.\n\n✨ Incluye:\n🚤 Transporte marítimo ida y regreso.\n🍹 Cóctel de bienvenida.\n🍽️ Almuerzo típico con opciones deliciosas.\n🏖️ Acceso a instalaciones y zonas de descanso.\n🏄 Actividades como kayak, paddle board y beach tennis.\n💧 Botella de agua por persona.\n\n📌 Observaciones Importantes:\n• Impuesto portuario no incluido.\n• Ideal para familias y parejas.\n\n⏰ Horario:\n8:00 a.m. – 3:00 p.m.` },
  { name: 'PLAYA TRANQUILA + OCEANARIO MAR', price: 200000, cost: 160000, description: `¡Combinación perfecta de relax y vida marina! 🐬🏖️\nDisfruta de las arenas blancas de Playa Tranquila en Barú y conoce la riqueza marina del Caribe visitando el Oceanario.\n\n✨ Incluye:\n🚐 Transporte: Terrestre hasta Barú y marítimo hacia el oceanario.\n🎫 Entrada al Oceanario: Show de delfines y tiburones incluido.\n🏖️ Descanso: Tiempo libre en Playa Tranquila.\n🍽️ Almuerzo Típico: Menú caribeño a elegir.\n⛱️ Instalaciones: Uso de sillas en el club de playa.\n\n📌 Observaciones Importantes:\n• El traslado entre Barú y el Oceanario se hace en lancha rápida.\n\n⏰ Horario:\n7:00 a.m. – 3:00 p.m.` },
  { name: 'PLAYA TRANQUILA +MAPACHES + BAJO', price: 270000, cost: 190000, description: `¡Aventura y naturaleza en Playa Tranquila Barú! 🦝🌊\nDescansa en la playa, interactúa con adorables mapaches en su hábitat y explora hermosas zonas de bajo para nadar tranquilamente.\n\n✨ Incluye:\n🚐 Transporte: Terrestre y marítimo (lancha corta).\n🏖️ Ubicación: Sector exclusivo en Playa Tranquila.\n🦝 Avistamiento de Mapaches: Interacción guiada y fotos con mapaches en zona de manglares.\n🏊‍♂️ Parada en 'El Bajo': Zona de aguas cristalinas poco profundas en medio del mar.\n🍽️ Almuerzo Típico: Deliciosa comida costeña.\n⛱️ Asoleadoras: Espacio reservado para descansar.\n\n📌 Observaciones Importantes:\n• Cuidar de no alimentar a los animales con comida no autorizada por los guías.\n\n⏰ Horario:\n7:00 a.m. – 3:00 p.m.` },
  { name: 'PLAYA TRANQUILA PACK X 4 ADVENTURE', price: 1050000, cost: 735000, description: `¡Vive una experiencia personalizada en Playa Tranquila, Barú! 🌊✨\nPerfecta para quienes buscan comodidad, buen servicio y contacto con la naturaleza. Relájate en asoleadoras, observa manglares y mapaches y sumérgete en una aventura de snorkel.\n\n✨ Incluye:\n🤝 Servicio personalizado y dedicado durante todo el día.\n😎 Asoleadoras, zonas de descanso, áreas sociales y espacios sombreados.\n🐾 Avistamiento de manglares y mapaches.\n🤿 Snorkel guiado con peces tropicales.\n🍽️ Almuerzo incluido.\n\n📌 Observaciones Importantes:\n• Ideal para familias y grupos de amigos que quieren evitar vendedores y tener atención privada.\n\n⏰ Horario:\n7:00 a.m. – 3:00 p.m.` },
  { name: 'ROSARIO BEACH', price: 370000, cost: 300000, description: `¡Disfruta un día inolvidable en Rosario Beach! 🌴☀️\nEscápate a las Islas del Rosario y vive una experiencia única frente al mar. Relájate en playas paradisíacas y diviértete con actividades acuáticas.\n\n✨ Incluye:\n🚤 Transporte marítimo ida y regreso.\n🍹 Cóctel de bienvenida.\n🍽️ Almuerzo típico con opciones deliciosas.\n🏖️ Acceso a instalaciones y zonas de descanso exclusivas.\n🏄 Actividades como kayak y paddle board.\n💧 Botella de agua por persona.\n\n📌 Observaciones Importantes:\n• Impuesto portuario no incluido.\n\n⏰ Horario:\n8:00 a.m. – 3:00 p.m.` },
  { name: 'SANTA MARTA PLAYA BLANCA + ACUARIO', price: 180000, cost: 140000, description: `¡Descubre la magia de Santa Marta desde Cartagena! 🚌🐬\nExcursión a Santa Marta para visitar su emblemática Playa Blanca y el famoso Acuario El Rodadero.\n\n✨ Incluye:\n🚐 Transporte: Intermunicipal climatizado ida y regreso desde Cartagena.\n🚤 Lancha al Acuario: Traslado marítimo desde El Rodadero.\n🎫 Entradas Incluidas: Ingreso al Acuario para ver delfines, focas y tortugas marinas.\n🏖️ Playa Blanca (Santa Marta): Tiempo para relajarse en sus aguas calmadas.\n🍽️ Alimentación: Desayuno ligero y Almuerzo típico samario.\n\n📌 Observaciones Importantes:\n• Viaje largo de 4 horas por trayecto, se sale de madrugada.\n\n⏰ Horario:\n4:00 a.m. – 9:00 p.m.` },
  { name: 'SUNSET CATAMARAN FLAMANTE', price: 200000, cost: 160000, description: `¡El mejor atardecer del Caribe lo vives a bordo del Flamante! ⛵🌅\nDisfruta del espectacular atardecer cartagenero navegando por la bahía en un lujoso catamarán con bebidas y excelente música.\n\n✨ Incluye:\n⛵ Navegación: 2 horas de recorrido por la bahía a bordo de un catamarán de lujo.\n🍹 Bebidas: Barra libre (agua, jugos, sodas) o copa de vino de bienvenida.\n🎶 Ambiente: Música chillout / DJ en vivo para acompañar el atardecer.\n📸 Vistas Panorámicas: El mejor ángulo para ver la ciudad amurallada y Bocagrande al caer el sol.\n🍤 Pasabocas: Pequeño snack de cortesía.\n\n📌 Observaciones Importantes:\n• Impuesto de muelle no incluido.\n\n⏰ Horario:\n5:00 p.m. – 7:00 p.m.` },
  { name: 'TOP 3 BORA BORA', price: 510000, cost: 430000, description: `¡La ruta exclusiva por las Islas del Rosario coronada en Bora Bora! 🚤👑\nEl recorrido definitivo que incluye visita a varias islas y una parada principal en el famoso Bora Bora Beach Club, garantizando lujo y diversión.\n\n✨ Incluye:\n🚤 Transporte: Lancha rápida ida y regreso.\n🌅 Tour Panorámico: Avistamiento de diferentes islas del archipiélago.\n🍹 Cóctel de Bienvenida: Recepción al llegar al Beach Club.\n🏖️ Bora Bora Beach Club: Acceso a instalaciones y asoleadoras.\n🍽️ Almuerzo Gourmet: Menú exclusivo de alta cocina.\n🎧 Fiesta: Animación y DJ en vivo.\n\n📌 Observaciones Importantes:\n• Solo adultos.\n• Tasa portuaria no incluida.\n\n⏰ Horario:\n8:00 a.m. – 3:00 p.m.` },
  { name: 'TOP 3 ISLAS - BORA BORA | PAO PAO | ISLABELA', price: 510000, cost: 357000, description: `Vive una experiencia única visitando tres de las mejores islas del Caribe colombiano en un solo día: Bora Bora Beach Club, Pao Pao Hotel & Restaurant e Islabela.\n\n✨ Incluye:\n🚤 Transporte en lancha rápida.\n🗣️ Guía bilingüe.\n🌅 Recorrido panorámico por las Islas del Rosario.\n🍹 Trago de bienvenida en CADA isla.\n💧 Agua fresca a bordo.\n🍽️ 3 opciones de almuerzo + bebida en Islabela.\n⛱️ Espacios disponibles para disfrutar en cada isla.\n\n📌 Observaciones Importantes:\n• Punto de encuentro: Muelle La Bodeguita – 8:00 a.m.\n• Solo adultos (18+).\n• No incluye tasa portuaria ni seguro.\n\n⏰ Horario:\n8:00 a.m. – 3:00 p.m.` },
  { name: 'TOP 3 ISLAS PRIVADAS', price: 380000, cost: 310000, description: `¡Un día, tres experiencias de lujo en islas privadas! 🏝️💎\nVisita las mejores islas exclusivas del Rosario en lancha rápida, disfrutando de lo mejor de la gastronomía, playas y confort.\n\n✨ Incluye:\n🚤 Transporte: Lancha rápida deportiva compartida.\n🏝️ Isla 1: Parada en un club de playa para disfrutar del mar y un cóctel de bienvenida.\n🏖️ Isla 2: Visita a una segunda isla privada para relajación.\n🍽️ Isla 3 (Principal): Parada para el almuerzo a la carta y uso de asoleadoras.\n🤿 Snorkel: Equipo básico incluido para realizar inmersiones cortas.\n\n📌 Observaciones Importantes:\n• Impuesto portuario no incluido.\n• Solo adultos o familias previa consulta.\n\n⏰ Horario:\n8:00 a.m. – 3:00 p.m.` },
  { name: 'TOUR BAHIA EN BOTE', price: 90000, cost: 55000, description: `¡La belleza de Cartagena desde el mar al atardecer o la noche! 🚤🌉\nRelajante recorrido de dos horas navegando por la bahía interna, observando la ciudad moderna y colonial iluminada.\n\n✨ Incluye:\n🚤 Transporte: Bote deportivo / lanchón espacioso.\n🎶 Entretenimiento: Música crossover a bordo.\n🍻 Bebidas: Barra libre de bebidas nacionales (Cuba Libre, jugos).\n🏙️ Recorrido: Vistas de Castillogrande, Manga, Centro y Pegasos.\n\n📌 Observaciones Importantes:\n• Punto de encuentro en Muelle de los Pegasos (No requiere pago de impuesto portuario).\n\n⏰ Horario:\nSalidas 5:00 p.m. o 7:00 p.m.` },
  { name: 'TOUR ISLAS DEL ROSARIO + BARU - FULL DAY', price: 180000, cost: 125999, description: `¡Un plan ultra completo! Tour combinado por Islas del Rosario y Playa Blanca Barú, ideal para explorar varias zonas del Caribe en un solo día.\n\n✨ Incluye:\n🚌 Transporte ida y regreso en bus climatizado hacia Barú.\n🚤 Transporte en lancha ida y regreso desde Barú hacia Islas del Rosario.\n🪶 Parada en San Martín de Pajarales (acuífero natural).\n🐬 Parada en el Oceanario (No incluye entrada).\n🍽️ Almuerzo típico caribeño (Pollo, Pescado, Cerdo o Vegetariano).\n👨‍✈️ Guía turístico acompañante.\n\n📌 Observaciones Importantes:\n• Oceanario y Snorkel no incluidos en el precio.\n• Carpas y parasoles no incluidos.\n\n⏰ Horario:\n7:00 a.m. – 3:00 p.m.` },
  { name: 'TOUR PLAYA TRANQUILA - ISLA BARU', price: 170000, cost: 118999, description: `¡Vive un día de relax total en Playa Tranquila! Un sector encantador de Barú para desconectarte del ruido de la ciudad.\n\n✨ Incluye:\n🚌 Transporte terrestre hasta Playa Blanca – Barú.\n🚤 Transporte en lancha (10 min) hacia el sector exclusivo de Playa Tranquila.\n🍹 Bebida de bienvenida.\n⛱️ Uso de instalaciones (Sombrillas, Camas asoleadoras, Zonas de descanso).\n🍽️ Almuerzo típico caribeño (Pollo, Pescado, Cerdo, Vegetariano).\n👨‍✈️ Guía personalizado.\n\n📌 Observaciones Importantes:\n• Recogida incluida en Bocagrande, Laguito, Castillogrande, Marbella, Crespo.\n\n⏰ Horario:\n7:00 a.m. – 3:00 p.m.` },
  { name: 'TOUR PUNTA ARENA - ISLA TIERRA BOMBA', price: 80000, cost: 56000, description: `¡Disfruta un día espectacular y relajado en Punta Arena, Isla Tierra Bomba! 🚤⛱️\nIdeal para quienes buscan un ambiente tranquilo, aguas claras y excelente vista a la ciudad.\n\n✨ Incluye:\n🚤 Transporte ida y vuelta en lancha hacia Punta Arena (10 min de viaje).\n🍽️ Almuerzo típico caribeño (Pollo, Pescado, Cerdo, Vegetariano).\n🌴 Zonas de descanso (Sillas, Mesas).\n🎵 Música ambiental para disfrutar la playa.\n\n📌 Observaciones Importantes:\n• No incluye recogida en el hotel ni gastos no especificados.\n\n⏰ Horario:\nSalidas: 8:30 a.m., 9:30 a.m., 10:30 a.m.\nRegresos: 3:00 p.m. y 4:30 p.m.` },
  { name: 'TOUR VOLAR - CARTAGENA DESDE EL CIELO', price: 160000, cost: 112000, description: `¡Sobrevuela Cartagena en Helicóptero y disfruta de un club con show en vivo! 🚁🛥️\n\n✨ Incluye:\n🍸 Cóctel de bienvenida.\n🕺 DJ + show de bailarines en la base.\n🍽️ Almuerzo tipo buffet (Lomo de cerdo, Pescado, Pollo).\n🚁 Vuelo panorámico en helicóptero (12 km) para una vista increíble de la ciudad.\n\n📌 Observaciones Importantes:\n• No apto para mujeres embarazadas.\n• Impuesto portuario/de despegue: $18.000 COP por persona extra.\n• NOTA: El valor base ($160.000) a veces corresponde solo al pasadía, confirmar tarifa del vuelo panorámico.\n\n⏰ Horario:\nMuelle la Bodeguita puerta #1 (9:30 a.m.). Regreso: 2:30 p.m.` },
  { name: 'TOURS 5 ISLAS FULL TERRESTRE', price: 250000, cost: 175000, description: `¡Vive la experiencia definitiva en el Caribe con el Tour 5 Islas Full Day Terrestre! 🌴✨\nDiseñado para los viajeros más exigentes que buscan una aventura inmersiva, vibrante y llena de contrastes.\n\n✨ Incluye:\n🚐 Transporte: Cómoda recogida en bus climatizado desde tu hotel hasta Barú.\n🚤 Transporte en Lancha: Recorrido marítimo seguro por las islas.\n🌅 Tour Panorámico: Archipiélago de las Islas del Rosario.\n🏖️ Isla Privada Kokomo: Relájate en un entorno exclusivo.\n🤿 Snorkeling de Aventura: Avioneta hundida de Pablo Escobar.\n🏝️ Fiesta en Isla Cholón: Cóctel de mariscos de cortesía y bohío.\n🌊 Playa Tranquila: Relajación total e instalaciones.\n🍽️ Almuerzo Típico: Gastronomía local.\n🌌 Avistamiento de Plancton: Nada en aguas bioluminiscentes de noche.\n⛴️ Retorno: Bus climatizado a Cartagena.\n\n📌 Observaciones Importantes:\n• Oceanario: La visita es opcional y se paga directo en el lugar.\n• Tiempo libre de 50 minutos en el oceanario (puedes hacer snorkel).\n• No incluye bebidas adicionales.\n\n⏰ Horario:\n7:00 a.m. – 8:00 p.m.` },
  { name: 'TOURS BAHIA + CLUB DE PLAYA KABANA', price: 200000, cost: 120000, description: `¡Disfruta de la NOCHE AZUL! 🌊✨\nUn recorrido en bote deportivo por la bahía y pasadía nocturno en el espectacular Club Kabanna en Isla Tierra Bomba.\n\n✨ Incluye:\n🚤 Recorrido de 1:30 h en bote deportivo por la bahía.\n🥂 Barra libre durante la navegación (Cuba Libre y Aguardiente).\n🎶 Música variada con Animación.\n🏝️ Acceso a Club Kabanna en Isla Tierra Bomba (2-4 horas).\n🏊 Uso de playa exclusiva y piscina.\n💃 Disco bar entrada incluida.\n🥘 Cena: Picadas de mariscos, chicharrón o pollo.\n\n📌 Observaciones Importantes:\n• Punto de encuentro: Muelle Los Pegasos.\n\n⏰ Horario:\nSalida: 5:00 p.m y 7:00 p.m.\nRegreso: 9:00 p.m. y 11:00 p.m.` },
  { name: 'TOURS BAHIA BARCO PIRATA', price: 130000, cost: 80000, description: `¡Aborda el Barco Pirata y vive una aventura mágica por la bahía! 🏴‍☠️⚔️\nDiversión familiar asegurada. Navega al atardecer o noche con recreación dirigida y un gran espectáculo corsario.\n\n✨ Incluye:\n🚢 Navegación: 2 horas de recorrido a bordo de la réplica del Barco Pirata.\n🍹 Bebidas: Refresco o cerveza de bienvenida.\n🎭 Espectáculo: Show pirata interactivo, juegos y bailes.\n📸 Fotografías: Espacios temáticos para tomarse fotos increíbles.\n🎉 Ambiente: Ideal para niños y adultos con espíritu joven.\n\n📌 Observaciones Importantes:\n• Tasa portuaria no incluida.\n• No incluye cena.\n\n⏰ Horario:\n5:00 p.m. o 7:00 p.m.` },
  { name: 'TOURS BAHIA BEQUIA EAGLE', price: 150000, cost: 110000, description: `¡Navega la bahía en la emblemática embarcación Bequia Eagle! 🚢🥂\nDisfruta de la brisa marina y las luces de la ciudad iluminada con música en vivo y ambiente festivo.\n\n✨ Incluye:\n🚢 Transporte: Recorrido panorámico por la bahía interna.\n🎶 Entretenimiento: Animador y música crossover a bordo.\n🍻 Bebidas: Cóctel de bienvenida o barra libre (según opción).\n🏙️ Vistas: Panorámicas de Bocagrande, Manga y la Ciudad Amurallada.\n\n📌 Observaciones Importantes:\n• Impuesto portuario no incluido.\n• Ambiente familiar y de fiesta.\n\n⏰ Horario:\n5:00 p.m. o 7:00 p.m.` },
  { name: 'TOURS VOLCAN DEL TOTUMO', price: 170000, cost: 110000, description: `¡Un viaje curativo, divertido y lleno de lodo! 🌋🧖‍♂️\nSumérgete en el famoso lodo terapéutico del cráter del Volcán del Totumo y luego refréscate en la laguna cercana.\n\n✨ Incluye:\n🚐 Transporte: Bus climatizado ida y regreso.\n🌋 Entrada al Volcán: Acceso al cráter para el baño de lodo.\n🌊 Lavado: Acceso a la ciénaga del Totumo para retirarse el lodo.\n🍽️ Almuerzo Típico: Pescado, arroz con coco y patacones en Manzanillo del Mar (opcional según el paquete).\n👨‍✈️ Guía Acompañante: Asistencia general.\n\n📌 Observaciones Importantes:\n• El servicio de masajes, fotos y asistencia para lavarse el lodo que ofrecen los locales no está incluido y requiere propina directa.\n\n⏰ Horario:\n8:30 a.m. – 3:00 p.m.` }
]

